//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.08 at 02:41:59 PM ICT 
//


package th.go.excise.edbarcode.ws.oxm;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for alcoholTaxFormSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="alcoholTaxFormSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sumTaxByValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="sumTaxByCapacity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="reductTaxProduct" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="receipt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reduceTaxProductBaht" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="reduceTaxByDepBookNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reduceTaxByDepBookNoBaht" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxRateByMOI" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxByMOI" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="other" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxByThaiHealth" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxByThaiPBS" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxByNSDF" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "alcoholTaxFormSummary", propOrder = {
    "sumTaxByValue",
    "sumTaxByCapacity",
    "reductTaxProduct",
    "receipt",
    "reduceTaxProductBaht",
    "reduceTaxByDepBookNo",
    "reduceTaxByDepBookNoBaht",
    "taxRateByMOI",
    "taxByMOI",
    "other",
    "taxByThaiHealth",
    "taxByThaiPBS",
    "taxByNSDF"
})
public class AlcoholTaxFormSummary {

    @XmlElement(required = true)
    protected BigDecimal sumTaxByValue;
    @XmlElement(required = true)
    protected BigDecimal sumTaxByCapacity;
    @XmlElement(required = true)
    protected BigDecimal reductTaxProduct;
    @XmlElement(required = true)
    protected String receipt;
    @XmlElement(required = true)
    protected BigDecimal reduceTaxProductBaht;
    @XmlElement(required = true)
    protected String reduceTaxByDepBookNo;
    @XmlElement(required = true)
    protected BigDecimal reduceTaxByDepBookNoBaht;
    @XmlElement(required = true)
    protected BigDecimal taxRateByMOI;
    @XmlElement(required = true)
    protected BigDecimal taxByMOI;
    @XmlElement(required = true)
    protected BigDecimal other;
    @XmlElement(required = true)
    protected BigDecimal taxByThaiHealth;
    @XmlElement(required = true)
    protected BigDecimal taxByThaiPBS;
    @XmlElement(required = true)
    protected BigDecimal taxByNSDF;

    /**
     * Gets the value of the sumTaxByValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSumTaxByValue() {
        return sumTaxByValue;
    }

    /**
     * Sets the value of the sumTaxByValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSumTaxByValue(BigDecimal value) {
        this.sumTaxByValue = value;
    }

    /**
     * Gets the value of the sumTaxByCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSumTaxByCapacity() {
        return sumTaxByCapacity;
    }

    /**
     * Sets the value of the sumTaxByCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSumTaxByCapacity(BigDecimal value) {
        this.sumTaxByCapacity = value;
    }

    /**
     * Gets the value of the reductTaxProduct property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReductTaxProduct() {
        return reductTaxProduct;
    }

    /**
     * Sets the value of the reductTaxProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReductTaxProduct(BigDecimal value) {
        this.reductTaxProduct = value;
    }

    /**
     * Gets the value of the receipt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceipt() {
        return receipt;
    }

    /**
     * Sets the value of the receipt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceipt(String value) {
        this.receipt = value;
    }

    /**
     * Gets the value of the reduceTaxProductBaht property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReduceTaxProductBaht() {
        return reduceTaxProductBaht;
    }

    /**
     * Sets the value of the reduceTaxProductBaht property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReduceTaxProductBaht(BigDecimal value) {
        this.reduceTaxProductBaht = value;
    }

    /**
     * Gets the value of the reduceTaxByDepBookNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReduceTaxByDepBookNo() {
        return reduceTaxByDepBookNo;
    }

    /**
     * Sets the value of the reduceTaxByDepBookNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReduceTaxByDepBookNo(String value) {
        this.reduceTaxByDepBookNo = value;
    }

    /**
     * Gets the value of the reduceTaxByDepBookNoBaht property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReduceTaxByDepBookNoBaht() {
        return reduceTaxByDepBookNoBaht;
    }

    /**
     * Sets the value of the reduceTaxByDepBookNoBaht property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReduceTaxByDepBookNoBaht(BigDecimal value) {
        this.reduceTaxByDepBookNoBaht = value;
    }

    /**
     * Gets the value of the taxRateByMOI property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxRateByMOI() {
        return taxRateByMOI;
    }

    /**
     * Sets the value of the taxRateByMOI property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxRateByMOI(BigDecimal value) {
        this.taxRateByMOI = value;
    }

    /**
     * Gets the value of the taxByMOI property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxByMOI() {
        return taxByMOI;
    }

    /**
     * Sets the value of the taxByMOI property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxByMOI(BigDecimal value) {
        this.taxByMOI = value;
    }

    /**
     * Gets the value of the other property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOther(BigDecimal value) {
        this.other = value;
    }

    /**
     * Gets the value of the taxByThaiHealth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxByThaiHealth() {
        return taxByThaiHealth;
    }

    /**
     * Sets the value of the taxByThaiHealth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxByThaiHealth(BigDecimal value) {
        this.taxByThaiHealth = value;
    }

    /**
     * Gets the value of the taxByThaiPBS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxByThaiPBS() {
        return taxByThaiPBS;
    }

    /**
     * Sets the value of the taxByThaiPBS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxByThaiPBS(BigDecimal value) {
        this.taxByThaiPBS = value;
    }

    /**
     * Gets the value of the taxByNSDF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxByNSDF() {
        return taxByNSDF;
    }

    /**
     * Sets the value of the taxByNSDF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxByNSDF(BigDecimal value) {
        this.taxByNSDF = value;
    }

}
