//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 03:16:25 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.excise.go.th/xsd/barcode")
package th.go.excise.edbarcode.ws.oxm;
