//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.02 at 03:09:05 PM ICT 
//


package th.go.excise.edbarcode.ws.oxm;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for productTax complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="productTax">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="recordNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productGroup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="degree" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="piece" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="capacityTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="sellingPriceByOwner" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="sellingPriceByDepartment" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxByValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxByCapacity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxByValuePlus" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productTax", propOrder = {
    "recordNo",
    "productGroup",
    "productName",
    "degree",
    "size",
    "piece",
    "capacityTax",
    "sellingPriceByOwner",
    "sellingPriceByDepartment",
    "taxByValue",
    "taxByCapacity",
    "taxByValuePlus"
})
public class ProductTax {

    @XmlElement(required = true)
    protected String recordNo;
    @XmlElement(required = true)
    protected String productGroup;
    @XmlElement(required = true)
    protected String productName;
    @XmlElement(required = true)
    protected BigDecimal degree;
    @XmlElement(required = true)
    protected BigDecimal size;
    @XmlElement(required = true)
    protected BigDecimal piece;
    @XmlElement(required = true)
    protected BigDecimal capacityTax;
    @XmlElement(required = true)
    protected BigDecimal sellingPriceByOwner;
    @XmlElement(required = true)
    protected BigDecimal sellingPriceByDepartment;
    @XmlElement(required = true)
    protected BigDecimal taxByValue;
    @XmlElement(required = true)
    protected BigDecimal taxByCapacity;
    @XmlElement(required = true)
    protected BigDecimal taxByValuePlus;

    /**
     * Gets the value of the recordNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordNo() {
        return recordNo;
    }

    /**
     * Sets the value of the recordNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordNo(String value) {
        this.recordNo = value;
    }

    /**
     * Gets the value of the productGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductGroup() {
        return productGroup;
    }

    /**
     * Sets the value of the productGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductGroup(String value) {
        this.productGroup = value;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the degree property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDegree() {
        return degree;
    }

    /**
     * Sets the value of the degree property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDegree(BigDecimal value) {
        this.degree = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSize(BigDecimal value) {
        this.size = value;
    }

    /**
     * Gets the value of the piece property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPiece() {
        return piece;
    }

    /**
     * Sets the value of the piece property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPiece(BigDecimal value) {
        this.piece = value;
    }

    /**
     * Gets the value of the capacityTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCapacityTax() {
        return capacityTax;
    }

    /**
     * Sets the value of the capacityTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCapacityTax(BigDecimal value) {
        this.capacityTax = value;
    }

    /**
     * Gets the value of the sellingPriceByOwner property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSellingPriceByOwner() {
        return sellingPriceByOwner;
    }

    /**
     * Sets the value of the sellingPriceByOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSellingPriceByOwner(BigDecimal value) {
        this.sellingPriceByOwner = value;
    }

    /**
     * Gets the value of the sellingPriceByDepartment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSellingPriceByDepartment() {
        return sellingPriceByDepartment;
    }

    /**
     * Sets the value of the sellingPriceByDepartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSellingPriceByDepartment(BigDecimal value) {
        this.sellingPriceByDepartment = value;
    }

    /**
     * Gets the value of the taxByValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxByValue() {
        return taxByValue;
    }

    /**
     * Sets the value of the taxByValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxByValue(BigDecimal value) {
        this.taxByValue = value;
    }

    /**
     * Gets the value of the taxByCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxByCapacity() {
        return taxByCapacity;
    }

    /**
     * Sets the value of the taxByCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxByCapacity(BigDecimal value) {
        this.taxByCapacity = value;
    }

    /**
     * Gets the value of the taxByValuePlus property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxByValuePlus() {
        return taxByValuePlus;
    }

    /**
     * Sets the value of the taxByValuePlus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxByValuePlus(BigDecimal value) {
        this.taxByValuePlus = value;
    }

}
