//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.08 at 02:28:24 PM ICT 
//


package th.go.excise.edbarcode.ws.oxm;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="product">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="productGroup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brandMajor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brandMinor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="degree" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxByValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxByCapacity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxByLiter" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="lowestDegreeNoTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxPlusByDegree" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="lowestSellingPriceNoTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxPlusBySellingPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="announcePriceDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="announcePriceValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "product", propOrder = {
    "productGroup",
    "productCode",
    "productName",
    "brandMajor",
    "brandMinor",
    "model",
    "size",
    "unit",
    "degree",
    "taxByValue",
    "taxByCapacity",
    "taxByLiter",
    "lowestDegreeNoTax",
    "taxPlusByDegree",
    "lowestSellingPriceNoTax",
    "taxPlusBySellingPrice",
    "announcePriceDate",
    "announcePriceValue"
})
public class Product {

    @XmlElement(required = true)
    protected String productGroup;
    @XmlElement(required = true)
    protected String productCode;
    @XmlElement(required = true)
    protected String productName;
    @XmlElement(required = true)
    protected String brandMajor;
    @XmlElement(required = true)
    protected String brandMinor;
    @XmlElement(required = true)
    protected String model;
    @XmlElement(required = true)
    protected BigDecimal size;
    @XmlElement(required = true)
    protected String unit;
    @XmlElement(required = true)
    protected BigDecimal degree;
    @XmlElement(required = true)
    protected BigDecimal taxByValue;
    @XmlElement(required = true)
    protected BigDecimal taxByCapacity;
    @XmlElement(required = true)
    protected BigDecimal taxByLiter;
    @XmlElement(required = true)
    protected BigDecimal lowestDegreeNoTax;
    @XmlElement(required = true)
    protected BigDecimal taxPlusByDegree;
    @XmlElement(required = true)
    protected BigDecimal lowestSellingPriceNoTax;
    @XmlElement(required = true)
    protected BigDecimal taxPlusBySellingPrice;
    @XmlElement(required = true)
    protected String announcePriceDate;
    @XmlElement(required = true)
    protected BigDecimal announcePriceValue;

    /**
     * Gets the value of the productGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductGroup() {
        return productGroup;
    }

    /**
     * Sets the value of the productGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductGroup(String value) {
        this.productGroup = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the brandMajor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrandMajor() {
        return brandMajor;
    }

    /**
     * Sets the value of the brandMajor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrandMajor(String value) {
        this.brandMajor = value;
    }

    /**
     * Gets the value of the brandMinor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrandMinor() {
        return brandMinor;
    }

    /**
     * Sets the value of the brandMinor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrandMinor(String value) {
        this.brandMinor = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSize(BigDecimal value) {
        this.size = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the degree property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDegree() {
        return degree;
    }

    /**
     * Sets the value of the degree property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDegree(BigDecimal value) {
        this.degree = value;
    }

    /**
     * Gets the value of the taxByValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxByValue() {
        return taxByValue;
    }

    /**
     * Sets the value of the taxByValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxByValue(BigDecimal value) {
        this.taxByValue = value;
    }

    /**
     * Gets the value of the taxByCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxByCapacity() {
        return taxByCapacity;
    }

    /**
     * Sets the value of the taxByCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxByCapacity(BigDecimal value) {
        this.taxByCapacity = value;
    }

    /**
     * Gets the value of the taxByLiter property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxByLiter() {
        return taxByLiter;
    }

    /**
     * Sets the value of the taxByLiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxByLiter(BigDecimal value) {
        this.taxByLiter = value;
    }

    /**
     * Gets the value of the lowestDegreeNoTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLowestDegreeNoTax() {
        return lowestDegreeNoTax;
    }

    /**
     * Sets the value of the lowestDegreeNoTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLowestDegreeNoTax(BigDecimal value) {
        this.lowestDegreeNoTax = value;
    }

    /**
     * Gets the value of the taxPlusByDegree property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxPlusByDegree() {
        return taxPlusByDegree;
    }

    /**
     * Sets the value of the taxPlusByDegree property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxPlusByDegree(BigDecimal value) {
        this.taxPlusByDegree = value;
    }

    /**
     * Gets the value of the lowestSellingPriceNoTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLowestSellingPriceNoTax() {
        return lowestSellingPriceNoTax;
    }

    /**
     * Sets the value of the lowestSellingPriceNoTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLowestSellingPriceNoTax(BigDecimal value) {
        this.lowestSellingPriceNoTax = value;
    }

    /**
     * Gets the value of the taxPlusBySellingPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxPlusBySellingPrice() {
        return taxPlusBySellingPrice;
    }

    /**
     * Sets the value of the taxPlusBySellingPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxPlusBySellingPrice(BigDecimal value) {
        this.taxPlusBySellingPrice = value;
    }

    /**
     * Gets the value of the announcePriceDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnouncePriceDate() {
        return announcePriceDate;
    }

    /**
     * Sets the value of the announcePriceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnouncePriceDate(String value) {
        this.announcePriceDate = value;
    }

    /**
     * Gets the value of the announcePriceValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAnnouncePriceValue() {
        return announcePriceValue;
    }

    /**
     * Sets the value of the announcePriceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAnnouncePriceValue(BigDecimal value) {
        this.announcePriceValue = value;
    }

}
