//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.12 at 07:09:10 PM ICT 
//


package th.go.excise.edbarcode.ws.client.pcc.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SR0112Form" type="{http://www.excise.go.th/xsd/barcode}SR0112Form" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormData", propOrder = {
    "sr0112Form"
})
public class FormData {

    @XmlElement(name = "SR0112Form")
    protected SR0112Form sr0112Form;

    /**
     * Gets the value of the sr0112Form property.
     * 
     * @return
     *     possible object is
     *     {@link SR0112Form }
     *     
     */
    public SR0112Form getSR0112Form() {
        return sr0112Form;
    }

    /**
     * Sets the value of the sr0112Form property.
     * 
     * @param value
     *     allowed object is
     *     {@link SR0112Form }
     *     
     */
    public void setSR0112Form(SR0112Form value) {
        this.sr0112Form = value;
    }

}
