//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.11 at 01:06:24 AM ICT 
//


package th.go.excise.edbarcode.ws.client.pcc.oxm;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GoodsEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GoodsEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GoodsInformation" type="{http://www.excise.go.th/xsd/barcode}GoodsInformation"/>
 *         &lt;element name="UnitCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RateFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TaxQuantity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TaxQuantityNumber" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TaxQuantityPerUnit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TaxValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="PriceFlag" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="InformPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="DeclarePrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="GoodsNum" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="GoodsValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TaxAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GoodsEntry", propOrder = {
    "goodsInformation",
    "unitCode",
    "rateFlag",
    "taxQuantity",
    "taxQuantityNumber",
    "taxQuantityPerUnit",
    "taxValue",
    "priceFlag",
    "informPrice",
    "declarePrice",
    "unitPrice",
    "goodsNum",
    "goodsValue",
    "taxAmount"
})
public class GoodsEntry {

    @XmlElement(name = "GoodsInformation", required = true)
    protected GoodsInformation goodsInformation;
    @XmlElement(name = "UnitCode", required = true)
    protected String unitCode;
    @XmlElement(name = "RateFlag", required = true)
    protected String rateFlag;
    @XmlElement(name = "TaxQuantity", required = true)
    protected BigDecimal taxQuantity;
    @XmlElement(name = "TaxQuantityNumber", required = true)
    protected BigDecimal taxQuantityNumber;
    @XmlElement(name = "TaxQuantityPerUnit", required = true)
    protected BigDecimal taxQuantityPerUnit;
    @XmlElement(name = "TaxValue", required = true)
    protected BigDecimal taxValue;
    @XmlElement(name = "PriceFlag", required = true)
    protected BigDecimal priceFlag;
    @XmlElement(name = "InformPrice", required = true)
    protected BigDecimal informPrice;
    @XmlElement(name = "DeclarePrice", required = true)
    protected BigDecimal declarePrice;
    @XmlElement(name = "UnitPrice", required = true)
    protected BigDecimal unitPrice;
    @XmlElement(name = "GoodsNum", required = true)
    protected BigDecimal goodsNum;
    @XmlElement(name = "GoodsValue", required = true)
    protected BigDecimal goodsValue;
    @XmlElement(name = "TaxAmount", required = true)
    protected BigDecimal taxAmount;

    /**
     * Gets the value of the goodsInformation property.
     * 
     * @return
     *     possible object is
     *     {@link GoodsInformation }
     *     
     */
    public GoodsInformation getGoodsInformation() {
        return goodsInformation;
    }

    /**
     * Sets the value of the goodsInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoodsInformation }
     *     
     */
    public void setGoodsInformation(GoodsInformation value) {
        this.goodsInformation = value;
    }

    /**
     * Gets the value of the unitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * Sets the value of the unitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitCode(String value) {
        this.unitCode = value;
    }

    /**
     * Gets the value of the rateFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateFlag() {
        return rateFlag;
    }

    /**
     * Sets the value of the rateFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateFlag(String value) {
        this.rateFlag = value;
    }

    /**
     * Gets the value of the taxQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxQuantity() {
        return taxQuantity;
    }

    /**
     * Sets the value of the taxQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxQuantity(BigDecimal value) {
        this.taxQuantity = value;
    }

    /**
     * Gets the value of the taxQuantityNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxQuantityNumber() {
        return taxQuantityNumber;
    }

    /**
     * Sets the value of the taxQuantityNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxQuantityNumber(BigDecimal value) {
        this.taxQuantityNumber = value;
    }

    /**
     * Gets the value of the taxQuantityPerUnit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxQuantityPerUnit() {
        return taxQuantityPerUnit;
    }

    /**
     * Sets the value of the taxQuantityPerUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxQuantityPerUnit(BigDecimal value) {
        this.taxQuantityPerUnit = value;
    }

    /**
     * Gets the value of the taxValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxValue() {
        return taxValue;
    }

    /**
     * Sets the value of the taxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxValue(BigDecimal value) {
        this.taxValue = value;
    }

    /**
     * Gets the value of the priceFlag property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPriceFlag() {
        return priceFlag;
    }

    /**
     * Sets the value of the priceFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPriceFlag(BigDecimal value) {
        this.priceFlag = value;
    }

    /**
     * Gets the value of the informPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInformPrice() {
        return informPrice;
    }

    /**
     * Sets the value of the informPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInformPrice(BigDecimal value) {
        this.informPrice = value;
    }

    /**
     * Gets the value of the declarePrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDeclarePrice() {
        return declarePrice;
    }

    /**
     * Sets the value of the declarePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDeclarePrice(BigDecimal value) {
        this.declarePrice = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitPrice(BigDecimal value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the goodsNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGoodsNum() {
        return goodsNum;
    }

    /**
     * Sets the value of the goodsNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGoodsNum(BigDecimal value) {
        this.goodsNum = value;
    }

    /**
     * Gets the value of the goodsValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGoodsValue() {
        return goodsValue;
    }

    /**
     * Sets the value of the goodsValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGoodsValue(BigDecimal value) {
        this.goodsValue = value;
    }

    /**
     * Gets the value of the taxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxAmount() {
        return taxAmount;
    }

    /**
     * Sets the value of the taxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxAmount(BigDecimal value) {
        this.taxAmount = value;
    }

}
