//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.11 at 01:06:24 AM ICT 
//


package th.go.excise.edbarcode.ws.client.pcc.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GoodsInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GoodsInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CategoryCode1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CategoryCode2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CategoryCode3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CategoryCode4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CategoryCode5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GoodsInformation", propOrder = {
    "productCode",
    "categoryCode1",
    "categoryCode2",
    "categoryCode3",
    "categoryCode4",
    "categoryCode5"
})
public class GoodsInformation {

    @XmlElement(name = "ProductCode", required = true)
    protected String productCode;
    @XmlElement(name = "CategoryCode1", required = true)
    protected String categoryCode1;
    @XmlElement(name = "CategoryCode2", required = true)
    protected String categoryCode2;
    @XmlElement(name = "CategoryCode3", required = true)
    protected String categoryCode3;
    @XmlElement(name = "CategoryCode4", required = true)
    protected String categoryCode4;
    @XmlElement(name = "CategoryCode5", required = true)
    protected String categoryCode5;

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the categoryCode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode1() {
        return categoryCode1;
    }

    /**
     * Sets the value of the categoryCode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode1(String value) {
        this.categoryCode1 = value;
    }

    /**
     * Gets the value of the categoryCode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode2() {
        return categoryCode2;
    }

    /**
     * Sets the value of the categoryCode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode2(String value) {
        this.categoryCode2 = value;
    }

    /**
     * Gets the value of the categoryCode3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode3() {
        return categoryCode3;
    }

    /**
     * Sets the value of the categoryCode3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode3(String value) {
        this.categoryCode3 = value;
    }

    /**
     * Gets the value of the categoryCode4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode4() {
        return categoryCode4;
    }

    /**
     * Sets the value of the categoryCode4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode4(String value) {
        this.categoryCode4 = value;
    }

    /**
     * Gets the value of the categoryCode5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode5() {
        return categoryCode5;
    }

    /**
     * Sets the value of the categoryCode5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode5(String value) {
        this.categoryCode5 = value;
    }

}
