//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.11 at 01:06:24 AM ICT 
//


package th.go.excise.edbarcode.ws.client.pcc.oxm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the th.go.excise.edbarcode.ws.client.pcc.oxm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: th.go.excise.edbarcode.ws.client.pcc.oxm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TaxpayerInformation }
     * 
     */
    public TaxpayerInformation createTaxpayerInformation() {
        return new TaxpayerInformation();
    }

    /**
     * Create an instance of {@link SubmissionInformation }
     * 
     */
    public SubmissionInformation createSubmissionInformation() {
        return new SubmissionInformation();
    }

    /**
     * Create an instance of {@link GoodsList }
     * 
     */
    public GoodsList createGoodsList() {
        return new GoodsList();
    }

    /**
     * Create an instance of {@link FundEntry }
     * 
     */
    public FundEntry createFundEntry() {
        return new FundEntry();
    }

    /**
     * Create an instance of {@link InsertSR12011OperationRequest }
     * 
     */
    public InsertSR12011OperationRequest createInsertSR12011OperationRequest() {
        return new InsertSR12011OperationRequest();
    }

    /**
     * Create an instance of {@link InquiryForm }
     * 
     */
    public InquiryForm createInquiryForm() {
        return new InquiryForm();
    }

    /**
     * Create an instance of {@link FormData }
     * 
     */
    public FormData createFormData() {
        return new FormData();
    }

    /**
     * Create an instance of {@link GoodsInformation }
     * 
     */
    public GoodsInformation createGoodsInformation() {
        return new GoodsInformation();
    }

    /**
     * Create an instance of {@link RequestHeader }
     * 
     */
    public RequestHeader createRequestHeader() {
        return new RequestHeader();
    }

    /**
     * Create an instance of {@link PS0112Form }
     * 
     */
    public PS0112Form createPS0112Form() {
        return new PS0112Form();
    }

    /**
     * Create an instance of {@link GoodsEntry }
     * 
     */
    public GoodsEntry createGoodsEntry() {
        return new GoodsEntry();
    }

    /**
     * Create an instance of {@link FundList }
     * 
     */
    public FundList createFundList() {
        return new FundList();
    }

    /**
     * Create an instance of {@link RequestBody }
     * 
     */
    public RequestBody createRequestBody() {
        return new RequestBody();
    }

    /**
     * Create an instance of {@link InsertSR12011OperationResponse }
     * 
     */
    public InsertSR12011OperationResponse createInsertSR12011OperationResponse() {
        return new InsertSR12011OperationResponse();
    }

    /**
     * Create an instance of {@link ResponseHeader }
     * 
     */
    public ResponseHeader createResponseHeader() {
        return new ResponseHeader();
    }

    /**
     * Create an instance of {@link ReponseBody }
     * 
     */
    public ReponseBody createReponseBody() {
        return new ReponseBody();
    }

    /**
     * Create an instance of {@link FormInformation }
     * 
     */
    public FormInformation createFormInformation() {
        return new FormInformation();
    }

}
