//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.12 at 07:09:10 PM ICT 
//


package th.go.excise.edbarcode.ws.client.pcc.oxm;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SR0112Form complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SR0112Form">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PaymentReferenceId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="BankReferenceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PayType12" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TaxMonth" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TaxYear" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="IncomeCode" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="FactoryDateBegin" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="FactoryDteEnd" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ExciseTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ReduceAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="PenaltyAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="SurchargeAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="MoiRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="MoiTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="SumCreditExciseTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="SumCreditMoiTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="NetExciseTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="NetMoiTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="PrnType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RecType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GoodsList" type="{http://www.excise.go.th/xsd/barcode}GoodsList" minOccurs="0"/>
 *         &lt;element name="FundList" type="{http://www.excise.go.th/xsd/barcode}FundList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SR0112Form", propOrder = {
    "paymentReferenceId",
    "bankReferenceId",
    "payType12",
    "taxMonth",
    "taxYear",
    "incomeCode",
    "factoryDateBegin",
    "factoryDteEnd",
    "exciseTax",
    "reduceAmt",
    "penaltyAmt",
    "surchargeAmt",
    "moiRate",
    "moiTax",
    "sumCreditExciseTax",
    "sumCreditMoiTax",
    "netExciseTax",
    "netMoiTax",
    "prnType",
    "recType",
    "goodsList",
    "fundList"
})
public class SR0112Form {

    @XmlElement(name = "PaymentReferenceId", required = true)
    protected BigInteger paymentReferenceId;
    @XmlElement(name = "BankReferenceId", required = true)
    protected String bankReferenceId;
    @XmlElement(name = "PayType12", required = true)
    protected String payType12;
    @XmlElement(name = "TaxMonth", required = true)
    protected BigDecimal taxMonth;
    @XmlElement(name = "TaxYear", required = true)
    protected BigDecimal taxYear;
    @XmlElement(name = "IncomeCode", required = true)
    protected BigDecimal incomeCode;
    @XmlElement(name = "FactoryDateBegin", required = true)
    protected BigDecimal factoryDateBegin;
    @XmlElement(name = "FactoryDteEnd", required = true)
    protected BigDecimal factoryDteEnd;
    @XmlElement(name = "ExciseTax", required = true)
    protected BigDecimal exciseTax;
    @XmlElement(name = "ReduceAmt", required = true)
    protected BigDecimal reduceAmt;
    @XmlElement(name = "PenaltyAmt", required = true)
    protected BigDecimal penaltyAmt;
    @XmlElement(name = "SurchargeAmt", required = true)
    protected BigDecimal surchargeAmt;
    @XmlElement(name = "MoiRate", required = true)
    protected BigDecimal moiRate;
    @XmlElement(name = "MoiTax", required = true)
    protected BigDecimal moiTax;
    @XmlElement(name = "SumCreditExciseTax", required = true)
    protected BigDecimal sumCreditExciseTax;
    @XmlElement(name = "SumCreditMoiTax", required = true)
    protected BigDecimal sumCreditMoiTax;
    @XmlElement(name = "NetExciseTax", required = true)
    protected BigDecimal netExciseTax;
    @XmlElement(name = "NetMoiTax", required = true)
    protected BigDecimal netMoiTax;
    @XmlElement(name = "PrnType")
    protected String prnType;
    @XmlElement(name = "RecType", required = true)
    protected String recType;
    @XmlElement(name = "GoodsList")
    protected GoodsList goodsList;
    @XmlElement(name = "FundList")
    protected FundList fundList;

    /**
     * Gets the value of the paymentReferenceId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPaymentReferenceId() {
        return paymentReferenceId;
    }

    /**
     * Sets the value of the paymentReferenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPaymentReferenceId(BigInteger value) {
        this.paymentReferenceId = value;
    }

    /**
     * Gets the value of the bankReferenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankReferenceId() {
        return bankReferenceId;
    }

    /**
     * Sets the value of the bankReferenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankReferenceId(String value) {
        this.bankReferenceId = value;
    }

    /**
     * Gets the value of the payType12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayType12() {
        return payType12;
    }

    /**
     * Sets the value of the payType12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayType12(String value) {
        this.payType12 = value;
    }

    /**
     * Gets the value of the taxMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxMonth() {
        return taxMonth;
    }

    /**
     * Sets the value of the taxMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxMonth(BigDecimal value) {
        this.taxMonth = value;
    }

    /**
     * Gets the value of the taxYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxYear() {
        return taxYear;
    }

    /**
     * Sets the value of the taxYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxYear(BigDecimal value) {
        this.taxYear = value;
    }

    /**
     * Gets the value of the incomeCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeCode() {
        return incomeCode;
    }

    /**
     * Sets the value of the incomeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeCode(BigDecimal value) {
        this.incomeCode = value;
    }

    /**
     * Gets the value of the factoryDateBegin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFactoryDateBegin() {
        return factoryDateBegin;
    }

    /**
     * Sets the value of the factoryDateBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFactoryDateBegin(BigDecimal value) {
        this.factoryDateBegin = value;
    }

    /**
     * Gets the value of the factoryDteEnd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFactoryDteEnd() {
        return factoryDteEnd;
    }

    /**
     * Sets the value of the factoryDteEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFactoryDteEnd(BigDecimal value) {
        this.factoryDteEnd = value;
    }

    /**
     * Gets the value of the exciseTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExciseTax() {
        return exciseTax;
    }

    /**
     * Sets the value of the exciseTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExciseTax(BigDecimal value) {
        this.exciseTax = value;
    }

    /**
     * Gets the value of the reduceAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReduceAmt() {
        return reduceAmt;
    }

    /**
     * Sets the value of the reduceAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReduceAmt(BigDecimal value) {
        this.reduceAmt = value;
    }

    /**
     * Gets the value of the penaltyAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPenaltyAmt() {
        return penaltyAmt;
    }

    /**
     * Sets the value of the penaltyAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPenaltyAmt(BigDecimal value) {
        this.penaltyAmt = value;
    }

    /**
     * Gets the value of the surchargeAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSurchargeAmt() {
        return surchargeAmt;
    }

    /**
     * Sets the value of the surchargeAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSurchargeAmt(BigDecimal value) {
        this.surchargeAmt = value;
    }

    /**
     * Gets the value of the moiRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMoiRate() {
        return moiRate;
    }

    /**
     * Sets the value of the moiRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMoiRate(BigDecimal value) {
        this.moiRate = value;
    }

    /**
     * Gets the value of the moiTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMoiTax() {
        return moiTax;
    }

    /**
     * Sets the value of the moiTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMoiTax(BigDecimal value) {
        this.moiTax = value;
    }

    /**
     * Gets the value of the sumCreditExciseTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSumCreditExciseTax() {
        return sumCreditExciseTax;
    }

    /**
     * Sets the value of the sumCreditExciseTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSumCreditExciseTax(BigDecimal value) {
        this.sumCreditExciseTax = value;
    }

    /**
     * Gets the value of the sumCreditMoiTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSumCreditMoiTax() {
        return sumCreditMoiTax;
    }

    /**
     * Sets the value of the sumCreditMoiTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSumCreditMoiTax(BigDecimal value) {
        this.sumCreditMoiTax = value;
    }

    /**
     * Gets the value of the netExciseTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetExciseTax() {
        return netExciseTax;
    }

    /**
     * Sets the value of the netExciseTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetExciseTax(BigDecimal value) {
        this.netExciseTax = value;
    }

    /**
     * Gets the value of the netMoiTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetMoiTax() {
        return netMoiTax;
    }

    /**
     * Sets the value of the netMoiTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetMoiTax(BigDecimal value) {
        this.netMoiTax = value;
    }

    /**
     * Gets the value of the prnType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrnType() {
        return prnType;
    }

    /**
     * Sets the value of the prnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrnType(String value) {
        this.prnType = value;
    }

    /**
     * Gets the value of the recType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecType() {
        return recType;
    }

    /**
     * Sets the value of the recType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecType(String value) {
        this.recType = value;
    }

    /**
     * Gets the value of the goodsList property.
     * 
     * @return
     *     possible object is
     *     {@link GoodsList }
     *     
     */
    public GoodsList getGoodsList() {
        return goodsList;
    }

    /**
     * Sets the value of the goodsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoodsList }
     *     
     */
    public void setGoodsList(GoodsList value) {
        this.goodsList = value;
    }

    /**
     * Gets the value of the fundList property.
     * 
     * @return
     *     possible object is
     *     {@link FundList }
     *     
     */
    public FundList getFundList() {
        return fundList;
    }

    /**
     * Sets the value of the fundList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundList }
     *     
     */
    public void setFundList(FundList value) {
        this.fundList = value;
    }

}
