//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.11 at 01:06:24 AM ICT 
//


package th.go.excise.edbarcode.ws.client.pcc.oxm;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubmissionInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubmissionInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IpAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InternetId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubmissionEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubmitDateTime" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubmissionInformation", propOrder = {
    "ipAddress",
    "internetId",
    "submissionEmail",
    "submitDateTime"
})
public class SubmissionInformation {

    @XmlElement(name = "IpAddress", required = true)
    protected String ipAddress;
    @XmlElement(name = "InternetId")
    protected String internetId;
    @XmlElement(name = "SubmissionEmail")
    protected String submissionEmail;
    @XmlElement(name = "SubmitDateTime", required = true)
    protected BigDecimal submitDateTime;

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpAddress(String value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the internetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternetId() {
        return internetId;
    }

    /**
     * Sets the value of the internetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternetId(String value) {
        this.internetId = value;
    }

    /**
     * Gets the value of the submissionEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmissionEmail() {
        return submissionEmail;
    }

    /**
     * Sets the value of the submissionEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmissionEmail(String value) {
        this.submissionEmail = value;
    }

    /**
     * Gets the value of the submitDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubmitDateTime() {
        return submitDateTime;
    }

    /**
     * Sets the value of the submitDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSubmitDateTime(BigDecimal value) {
        this.submitDateTime = value;
    }

}
