//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.11 at 12:25:38 AM ICT 
//


package th.go.excise.edbarcode.ws.client.sta.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Body complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Body">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Error" type="{http://www.example.org/StaBacSchema}Error" minOccurs="0"/>
 *         &lt;element name="DataInformation" type="{http://www.example.org/StaBacSchema}DataInformation" minOccurs="0"/>
 *         &lt;element name="BinaryInformation" type="{http://www.example.org/StaBacSchema}BinaryInformation" minOccurs="0"/>
 *         &lt;element name="ReferenceId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Body", propOrder = {

})
public class Body {

    @XmlElement(name = "Error")
    protected Error error;
    @XmlElement(name = "DataInformation")
    protected DataInformation dataInformation;
    @XmlElement(name = "BinaryInformation")
    protected BinaryInformation binaryInformation;
    @XmlElement(name = "ReferenceId")
    protected String referenceId;

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link Error }
     *     
     */
    public Error getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link Error }
     *     
     */
    public void setError(Error value) {
        this.error = value;
    }

    /**
     * Gets the value of the dataInformation property.
     * 
     * @return
     *     possible object is
     *     {@link DataInformation }
     *     
     */
    public DataInformation getDataInformation() {
        return dataInformation;
    }

    /**
     * Sets the value of the dataInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataInformation }
     *     
     */
    public void setDataInformation(DataInformation value) {
        this.dataInformation = value;
    }

    /**
     * Gets the value of the binaryInformation property.
     * 
     * @return
     *     possible object is
     *     {@link BinaryInformation }
     *     
     */
    public BinaryInformation getBinaryInformation() {
        return binaryInformation;
    }

    /**
     * Sets the value of the binaryInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BinaryInformation }
     *     
     */
    public void setBinaryInformation(BinaryInformation value) {
        this.binaryInformation = value;
    }

    /**
     * Gets the value of the referenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceId() {
        return referenceId;
    }

    /**
     * Sets the value of the referenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceId(String value) {
        this.referenceId = value;
    }

}
