//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.11 at 12:50:04 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.excise.go.th/xsd/barcode")
package th.go.excise.edbarcode.ws.client.barcode.oxm;
