//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 05:53:09 PM ICT 
//


package th.go.excise.edbarcode.ws.pccws.oxm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the th.go.excise.edbarcode.ws.pccws.oxm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: th.go.excise.edbarcode.ws.pccws.oxm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PCCResponse }
     * 
     */
    public PCCResponse createPCCResponse() {
        return new PCCResponse();
    }

    /**
     * Create an instance of {@link ResponseHeader }
     * 
     */
    public ResponseHeader createResponseHeader() {
        return new ResponseHeader();
    }

    /**
     * Create an instance of {@link ReponseBody }
     * 
     */
    public ReponseBody createReponseBody() {
        return new ReponseBody();
    }

    /**
     * Create an instance of {@link PCCRequest }
     * 
     */
    public PCCRequest createPCCRequest() {
        return new PCCRequest();
    }

    /**
     * Create an instance of {@link RequestHeader }
     * 
     */
    public RequestHeader createRequestHeader() {
        return new RequestHeader();
    }

    /**
     * Create an instance of {@link RequestBody }
     * 
     */
    public RequestBody createRequestBody() {
        return new RequestBody();
    }

    /**
     * Create an instance of {@link InquiryForm }
     * 
     */
    public InquiryForm createInquiryForm() {
        return new InquiryForm();
    }

}
