//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.10 at 11:32:33 AM ICT 
//


package th.go.excise.edbarcode.ws.client.pcc.insert0112.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Fund complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Fund">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fundType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fundAmt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="fundRate" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="creditAmt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="netAmt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Fund", propOrder = {
    "fundType",
    "fundAmt",
    "fundRate",
    "creditAmt",
    "netAmt"
})
public class Fund {

    @XmlElement(required = true, nillable = true)
    protected String fundType;
    protected double fundAmt;
    protected double fundRate;
    protected double creditAmt;
    protected double netAmt;

    /**
     * Gets the value of the fundType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFundType() {
        return fundType;
    }

    /**
     * Sets the value of the fundType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFundType(String value) {
        this.fundType = value;
    }

    /**
     * Gets the value of the fundAmt property.
     * 
     */
    public double getFundAmt() {
        return fundAmt;
    }

    /**
     * Sets the value of the fundAmt property.
     * 
     */
    public void setFundAmt(double value) {
        this.fundAmt = value;
    }

    /**
     * Gets the value of the fundRate property.
     * 
     */
    public double getFundRate() {
        return fundRate;
    }

    /**
     * Sets the value of the fundRate property.
     * 
     */
    public void setFundRate(double value) {
        this.fundRate = value;
    }

    /**
     * Gets the value of the creditAmt property.
     * 
     */
    public double getCreditAmt() {
        return creditAmt;
    }

    /**
     * Sets the value of the creditAmt property.
     * 
     */
    public void setCreditAmt(double value) {
        this.creditAmt = value;
    }

    /**
     * Gets the value of the netAmt property.
     * 
     */
    public double getNetAmt() {
        return netAmt;
    }

    /**
     * Sets the value of the netAmt property.
     * 
     */
    public void setNetAmt(double value) {
        this.netAmt = value;
    }

}
