//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.10 at 11:32:33 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bcsservice.pccth.com/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package th.go.excise.edbarcode.ws.client.pcc.insert0112.oxm;
