//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.10 at 11:32:33 AM ICT 
//


package th.go.excise.edbarcode.ws.client.pcc.insert0112.oxm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for POSO0112FormInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="POSO0112FormInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="registrationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="factoryId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pinNitId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="internetId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subbmissionEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="submitDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="formType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="formCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="formEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="formReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paymentReferenceId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bankReferenceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="payType12" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taxMonth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="taxYear" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="incomeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="factoryDateBegin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="factoryDateEnd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taxvalAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taxqtyAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="exciseTax" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="reduceAmt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="penaltyAmt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="surchargeAmt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="moiRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="moiTax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sumCreditExciseTax" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="sumCreditMoiTax" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="netExciseTax" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="netMoiTax" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="netSssTax" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="netSstTax" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="netKprTax" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="prnType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="recType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pso112Goods" type="{http://bcsservice.pccth.com/}PSO112Goods" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="fund" type="{http://bcsservice.pccth.com/}Fund" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="credit" type="{http://bcsservice.pccth.com/}Credit" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POSO0112FormInfo", propOrder = {
    "registrationId",
    "customerId",
    "factoryId",
    "tin",
    "pinNitId",
    "ipAddress",
    "internetId",
    "subbmissionEmail",
    "submitDateTime",
    "formType",
    "formCode",
    "formEffectiveDate",
    "formReferenceNumber",
    "paymentReferenceId",
    "bankReferenceId",
    "payType12",
    "taxMonth",
    "taxYear",
    "incomeCode",
    "factoryDateBegin",
    "factoryDateEnd",
    "taxvalAmt",
    "taxqtyAmt",
    "exciseTax",
    "reduceAmt",
    "penaltyAmt",
    "surchargeAmt",
    "moiRate",
    "moiTax",
    "sumCreditExciseTax",
    "sumCreditMoiTax",
    "netExciseTax",
    "netMoiTax",
    "netSssTax",
    "netSstTax",
    "netKprTax",
    "prnType",
    "recType",
    "pso112Goods",
    "fund",
    "credit"
})
public class POSO0112FormInfo {

    @XmlElement(required = true, nillable = true)
    protected String registrationId;
    @XmlElement(required = true, nillable = true)
    protected String customerId;
    @XmlElement(required = true, nillable = true)
    protected String factoryId;
    @XmlElement(required = true, nillable = true)
    protected String tin;
    @XmlElement(required = true, nillable = true)
    protected String pinNitId;
    @XmlElement(required = true, nillable = true)
    protected String ipAddress;
    @XmlElement(required = true, nillable = true)
    protected String internetId;
    @XmlElement(required = true, nillable = true)
    protected String subbmissionEmail;
    @XmlElement(required = true, nillable = true)
    protected String submitDateTime;
    @XmlElement(required = true, nillable = true)
    protected String formType;
    @XmlElement(required = true, nillable = true)
    protected String formCode;
    @XmlElement(required = true, nillable = true)
    protected String formEffectiveDate;
    @XmlElement(required = true, nillable = true)
    protected String formReferenceNumber;
    protected int paymentReferenceId;
    @XmlElement(required = true, nillable = true)
    protected String bankReferenceId;
    @XmlElement(required = true, nillable = true)
    protected String payType12;
    protected int taxMonth;
    protected int taxYear;
    @XmlElement(required = true, nillable = true)
    protected String incomeCode;
    @XmlElement(required = true, nillable = true)
    protected String factoryDateBegin;
    @XmlElement(required = true, nillable = true)
    protected String factoryDateEnd;
    @XmlElement(required = true, nillable = true)
    protected String taxvalAmt;
    @XmlElement(required = true, nillable = true)
    protected String taxqtyAmt;
    protected double exciseTax;
    protected double reduceAmt;
    protected double penaltyAmt;
    protected double surchargeAmt;
    @XmlElement(required = true, nillable = true)
    protected String moiRate;
    @XmlElement(required = true, nillable = true)
    protected String moiTax;
    protected double sumCreditExciseTax;
    protected double sumCreditMoiTax;
    protected double netExciseTax;
    protected double netMoiTax;
    protected double netSssTax;
    protected double netSstTax;
    protected double netKprTax;
    @XmlElement(required = true, nillable = true)
    protected String prnType;
    @XmlElement(required = true, nillable = true)
    protected String recType;
    @XmlElement(nillable = true)
    protected List<PSO112Goods> pso112Goods;
    @XmlElement(nillable = true)
    protected List<Fund> fund;
    @XmlElement(nillable = true)
    protected List<Credit> credit;

    /**
     * Gets the value of the registrationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationId() {
        return registrationId;
    }

    /**
     * Sets the value of the registrationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationId(String value) {
        this.registrationId = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerId(String value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the factoryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFactoryId() {
        return factoryId;
    }

    /**
     * Sets the value of the factoryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFactoryId(String value) {
        this.factoryId = value;
    }

    /**
     * Gets the value of the tin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTin() {
        return tin;
    }

    /**
     * Sets the value of the tin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTin(String value) {
        this.tin = value;
    }

    /**
     * Gets the value of the pinNitId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinNitId() {
        return pinNitId;
    }

    /**
     * Sets the value of the pinNitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinNitId(String value) {
        this.pinNitId = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpAddress(String value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the internetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternetId() {
        return internetId;
    }

    /**
     * Sets the value of the internetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternetId(String value) {
        this.internetId = value;
    }

    /**
     * Gets the value of the subbmissionEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubbmissionEmail() {
        return subbmissionEmail;
    }

    /**
     * Sets the value of the subbmissionEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubbmissionEmail(String value) {
        this.subbmissionEmail = value;
    }

    /**
     * Gets the value of the submitDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmitDateTime() {
        return submitDateTime;
    }

    /**
     * Sets the value of the submitDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmitDateTime(String value) {
        this.submitDateTime = value;
    }

    /**
     * Gets the value of the formType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormType() {
        return formType;
    }

    /**
     * Sets the value of the formType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormType(String value) {
        this.formType = value;
    }

    /**
     * Gets the value of the formCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormCode() {
        return formCode;
    }

    /**
     * Sets the value of the formCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormCode(String value) {
        this.formCode = value;
    }

    /**
     * Gets the value of the formEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormEffectiveDate() {
        return formEffectiveDate;
    }

    /**
     * Sets the value of the formEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormEffectiveDate(String value) {
        this.formEffectiveDate = value;
    }

    /**
     * Gets the value of the formReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormReferenceNumber() {
        return formReferenceNumber;
    }

    /**
     * Sets the value of the formReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormReferenceNumber(String value) {
        this.formReferenceNumber = value;
    }

    /**
     * Gets the value of the paymentReferenceId property.
     * 
     */
    public int getPaymentReferenceId() {
        return paymentReferenceId;
    }

    /**
     * Sets the value of the paymentReferenceId property.
     * 
     */
    public void setPaymentReferenceId(int value) {
        this.paymentReferenceId = value;
    }

    /**
     * Gets the value of the bankReferenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankReferenceId() {
        return bankReferenceId;
    }

    /**
     * Sets the value of the bankReferenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankReferenceId(String value) {
        this.bankReferenceId = value;
    }

    /**
     * Gets the value of the payType12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayType12() {
        return payType12;
    }

    /**
     * Sets the value of the payType12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayType12(String value) {
        this.payType12 = value;
    }

    /**
     * Gets the value of the taxMonth property.
     * 
     */
    public int getTaxMonth() {
        return taxMonth;
    }

    /**
     * Sets the value of the taxMonth property.
     * 
     */
    public void setTaxMonth(int value) {
        this.taxMonth = value;
    }

    /**
     * Gets the value of the taxYear property.
     * 
     */
    public int getTaxYear() {
        return taxYear;
    }

    /**
     * Sets the value of the taxYear property.
     * 
     */
    public void setTaxYear(int value) {
        this.taxYear = value;
    }

    /**
     * Gets the value of the incomeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncomeCode() {
        return incomeCode;
    }

    /**
     * Sets the value of the incomeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncomeCode(String value) {
        this.incomeCode = value;
    }

    /**
     * Gets the value of the factoryDateBegin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFactoryDateBegin() {
        return factoryDateBegin;
    }

    /**
     * Sets the value of the factoryDateBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFactoryDateBegin(String value) {
        this.factoryDateBegin = value;
    }

    /**
     * Gets the value of the factoryDateEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFactoryDateEnd() {
        return factoryDateEnd;
    }

    /**
     * Sets the value of the factoryDateEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFactoryDateEnd(String value) {
        this.factoryDateEnd = value;
    }

    /**
     * Gets the value of the taxvalAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxvalAmt() {
        return taxvalAmt;
    }

    /**
     * Sets the value of the taxvalAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxvalAmt(String value) {
        this.taxvalAmt = value;
    }

    /**
     * Gets the value of the taxqtyAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxqtyAmt() {
        return taxqtyAmt;
    }

    /**
     * Sets the value of the taxqtyAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxqtyAmt(String value) {
        this.taxqtyAmt = value;
    }

    /**
     * Gets the value of the exciseTax property.
     * 
     */
    public double getExciseTax() {
        return exciseTax;
    }

    /**
     * Sets the value of the exciseTax property.
     * 
     */
    public void setExciseTax(double value) {
        this.exciseTax = value;
    }

    /**
     * Gets the value of the reduceAmt property.
     * 
     */
    public double getReduceAmt() {
        return reduceAmt;
    }

    /**
     * Sets the value of the reduceAmt property.
     * 
     */
    public void setReduceAmt(double value) {
        this.reduceAmt = value;
    }

    /**
     * Gets the value of the penaltyAmt property.
     * 
     */
    public double getPenaltyAmt() {
        return penaltyAmt;
    }

    /**
     * Sets the value of the penaltyAmt property.
     * 
     */
    public void setPenaltyAmt(double value) {
        this.penaltyAmt = value;
    }

    /**
     * Gets the value of the surchargeAmt property.
     * 
     */
    public double getSurchargeAmt() {
        return surchargeAmt;
    }

    /**
     * Sets the value of the surchargeAmt property.
     * 
     */
    public void setSurchargeAmt(double value) {
        this.surchargeAmt = value;
    }

    /**
     * Gets the value of the moiRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoiRate() {
        return moiRate;
    }

    /**
     * Sets the value of the moiRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoiRate(String value) {
        this.moiRate = value;
    }

    /**
     * Gets the value of the moiTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoiTax() {
        return moiTax;
    }

    /**
     * Sets the value of the moiTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoiTax(String value) {
        this.moiTax = value;
    }

    /**
     * Gets the value of the sumCreditExciseTax property.
     * 
     */
    public double getSumCreditExciseTax() {
        return sumCreditExciseTax;
    }

    /**
     * Sets the value of the sumCreditExciseTax property.
     * 
     */
    public void setSumCreditExciseTax(double value) {
        this.sumCreditExciseTax = value;
    }

    /**
     * Gets the value of the sumCreditMoiTax property.
     * 
     */
    public double getSumCreditMoiTax() {
        return sumCreditMoiTax;
    }

    /**
     * Sets the value of the sumCreditMoiTax property.
     * 
     */
    public void setSumCreditMoiTax(double value) {
        this.sumCreditMoiTax = value;
    }

    /**
     * Gets the value of the netExciseTax property.
     * 
     */
    public double getNetExciseTax() {
        return netExciseTax;
    }

    /**
     * Sets the value of the netExciseTax property.
     * 
     */
    public void setNetExciseTax(double value) {
        this.netExciseTax = value;
    }

    /**
     * Gets the value of the netMoiTax property.
     * 
     */
    public double getNetMoiTax() {
        return netMoiTax;
    }

    /**
     * Sets the value of the netMoiTax property.
     * 
     */
    public void setNetMoiTax(double value) {
        this.netMoiTax = value;
    }

    /**
     * Gets the value of the netSssTax property.
     * 
     */
    public double getNetSssTax() {
        return netSssTax;
    }

    /**
     * Sets the value of the netSssTax property.
     * 
     */
    public void setNetSssTax(double value) {
        this.netSssTax = value;
    }

    /**
     * Gets the value of the netSstTax property.
     * 
     */
    public double getNetSstTax() {
        return netSstTax;
    }

    /**
     * Sets the value of the netSstTax property.
     * 
     */
    public void setNetSstTax(double value) {
        this.netSstTax = value;
    }

    /**
     * Gets the value of the netKprTax property.
     * 
     */
    public double getNetKprTax() {
        return netKprTax;
    }

    /**
     * Sets the value of the netKprTax property.
     * 
     */
    public void setNetKprTax(double value) {
        this.netKprTax = value;
    }

    /**
     * Gets the value of the prnType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrnType() {
        return prnType;
    }

    /**
     * Sets the value of the prnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrnType(String value) {
        this.prnType = value;
    }

    /**
     * Gets the value of the recType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecType() {
        return recType;
    }

    /**
     * Sets the value of the recType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecType(String value) {
        this.recType = value;
    }

    /**
     * Gets the value of the pso112Goods property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pso112Goods property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPso112Goods().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PSO112Goods }
     * 
     * 
     */
    public List<PSO112Goods> getPso112Goods() {
        if (pso112Goods == null) {
            pso112Goods = new ArrayList<PSO112Goods>();
        }
        return this.pso112Goods;
    }

    /**
     * Gets the value of the fund property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fund property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFund().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Fund }
     * 
     * 
     */
    public List<Fund> getFund() {
        if (fund == null) {
            fund = new ArrayList<Fund>();
        }
        return this.fund;
    }

    /**
     * Gets the value of the credit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the credit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCredit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Credit }
     * 
     * 
     */
    public List<Credit> getCredit() {
        if (credit == null) {
            credit = new ArrayList<Credit>();
        }
        return this.credit;
    }

}
