//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.13 at 08:52:57 PM ICT 
//


package th.go.excise.edbarcode.ws.client.pcc.insert0112.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PSO112Goods complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PSO112Goods">
 *   &lt;complexContent>
 *     &lt;extension base="{http://com.pccth.bcsservice/}GoodsInformation">
 *       &lt;sequence>
 *         &lt;element name="taxQuantityNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="declarePrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rateFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priceFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taxQuantityPerUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taxQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taxValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="informPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="unitPirce" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="goodsNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taxAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="goodsValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PSO112Goods", propOrder = {
    "taxQuantityNumber",
    "declarePrice",
    "rateFlag",
    "priceFlag",
    "taxQuantityPerUnit",
    "taxQuantity",
    "taxValue",
    "informPrice",
    "unitPirce",
    "goodsNum",
    "taxAmount",
    "goodsValue"
})
public class PSO112Goods
    extends GoodsInformation
{

    @XmlElement(required = true, nillable = true)
    protected String taxQuantityNumber;
    @XmlElement(required = true, nillable = true)
    protected String declarePrice;
    @XmlElement(required = true, nillable = true)
    protected String rateFlag;
    @XmlElement(required = true, nillable = true)
    protected String priceFlag;
    @XmlElement(required = true, nillable = true)
    protected String taxQuantityPerUnit;
    @XmlElement(required = true, nillable = true)
    protected String taxQuantity;
    @XmlElement(required = true, nillable = true)
    protected String taxValue;
    @XmlElement(required = true, nillable = true)
    protected String informPrice;
    @XmlElement(required = true, nillable = true)
    protected String unitPirce;
    @XmlElement(required = true, nillable = true)
    protected String goodsNum;
    @XmlElement(required = true, nillable = true)
    protected String taxAmount;
    @XmlElement(required = true, nillable = true)
    protected String goodsValue;

    /**
     * Gets the value of the taxQuantityNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxQuantityNumber() {
        return taxQuantityNumber;
    }

    /**
     * Sets the value of the taxQuantityNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxQuantityNumber(String value) {
        this.taxQuantityNumber = value;
    }

    /**
     * Gets the value of the declarePrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeclarePrice() {
        return declarePrice;
    }

    /**
     * Sets the value of the declarePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeclarePrice(String value) {
        this.declarePrice = value;
    }

    /**
     * Gets the value of the rateFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateFlag() {
        return rateFlag;
    }

    /**
     * Sets the value of the rateFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateFlag(String value) {
        this.rateFlag = value;
    }

    /**
     * Gets the value of the priceFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceFlag() {
        return priceFlag;
    }

    /**
     * Sets the value of the priceFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceFlag(String value) {
        this.priceFlag = value;
    }

    /**
     * Gets the value of the taxQuantityPerUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxQuantityPerUnit() {
        return taxQuantityPerUnit;
    }

    /**
     * Sets the value of the taxQuantityPerUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxQuantityPerUnit(String value) {
        this.taxQuantityPerUnit = value;
    }

    /**
     * Gets the value of the taxQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxQuantity() {
        return taxQuantity;
    }

    /**
     * Sets the value of the taxQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxQuantity(String value) {
        this.taxQuantity = value;
    }

    /**
     * Gets the value of the taxValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxValue() {
        return taxValue;
    }

    /**
     * Sets the value of the taxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxValue(String value) {
        this.taxValue = value;
    }

    /**
     * Gets the value of the informPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformPrice() {
        return informPrice;
    }

    /**
     * Sets the value of the informPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformPrice(String value) {
        this.informPrice = value;
    }

    /**
     * Gets the value of the unitPirce property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitPirce() {
        return unitPirce;
    }

    /**
     * Sets the value of the unitPirce property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitPirce(String value) {
        this.unitPirce = value;
    }

    /**
     * Gets the value of the goodsNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodsNum() {
        return goodsNum;
    }

    /**
     * Sets the value of the goodsNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsNum(String value) {
        this.goodsNum = value;
    }

    /**
     * Gets the value of the taxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxAmount() {
        return taxAmount;
    }

    /**
     * Sets the value of the taxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxAmount(String value) {
        this.taxAmount = value;
    }

    /**
     * Gets the value of the goodsValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodsValue() {
        return goodsValue;
    }

    /**
     * Sets the value of the goodsValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsValue(String value) {
        this.goodsValue = value;
    }

}
