//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.13 at 08:52:57 PM ICT 
//


package th.go.excise.edbarcode.ws.client.pcc.insert0112.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PSO130Goods complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PSO130Goods">
 *   &lt;complexContent>
 *     &lt;extension base="{http://com.pccth.bcsservice/}GoodsInformation">
 *       &lt;sequence>
 *         &lt;element name="taxQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="receiptNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="moiTax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taxValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="goodsNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="exciseTax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="receiptDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sumTax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PSO130Goods", propOrder = {
    "taxQuantity",
    "receiptNo",
    "moiTax",
    "taxValue",
    "goodsNum",
    "exciseTax",
    "receiptDate",
    "sumTax"
})
public class PSO130Goods
    extends GoodsInformation
{

    @XmlElement(required = true, nillable = true)
    protected String taxQuantity;
    @XmlElement(required = true, nillable = true)
    protected String receiptNo;
    @XmlElement(required = true, nillable = true)
    protected String moiTax;
    @XmlElement(required = true, nillable = true)
    protected String taxValue;
    @XmlElement(required = true, nillable = true)
    protected String goodsNum;
    @XmlElement(required = true, nillable = true)
    protected String exciseTax;
    @XmlElement(required = true, nillable = true)
    protected String receiptDate;
    @XmlElement(required = true, nillable = true)
    protected String sumTax;

    /**
     * Gets the value of the taxQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxQuantity() {
        return taxQuantity;
    }

    /**
     * Sets the value of the taxQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxQuantity(String value) {
        this.taxQuantity = value;
    }

    /**
     * Gets the value of the receiptNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiptNo() {
        return receiptNo;
    }

    /**
     * Sets the value of the receiptNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiptNo(String value) {
        this.receiptNo = value;
    }

    /**
     * Gets the value of the moiTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoiTax() {
        return moiTax;
    }

    /**
     * Sets the value of the moiTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoiTax(String value) {
        this.moiTax = value;
    }

    /**
     * Gets the value of the taxValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxValue() {
        return taxValue;
    }

    /**
     * Sets the value of the taxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxValue(String value) {
        this.taxValue = value;
    }

    /**
     * Gets the value of the goodsNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodsNum() {
        return goodsNum;
    }

    /**
     * Sets the value of the goodsNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsNum(String value) {
        this.goodsNum = value;
    }

    /**
     * Gets the value of the exciseTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExciseTax() {
        return exciseTax;
    }

    /**
     * Sets the value of the exciseTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExciseTax(String value) {
        this.exciseTax = value;
    }

    /**
     * Gets the value of the receiptDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiptDate() {
        return receiptDate;
    }

    /**
     * Sets the value of the receiptDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiptDate(String value) {
        this.receiptDate = value;
    }

    /**
     * Gets the value of the sumTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSumTax() {
        return sumTax;
    }

    /**
     * Sets the value of the sumTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSumTax(String value) {
        this.sumTax = value;
    }

}
