//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.26 at 09:32:28 PM ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Address complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Address">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HouseIdNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BuildingName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RoomNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FloorNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VillageName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HouseNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MooNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TrokSoiName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ThambolCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ThambolName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AmphurCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AmphurName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProvinceCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProvinceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Postcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TelNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Address", propOrder = {
    "houseIdNumber",
    "buildingName",
    "roomNumber",
    "floorNumber",
    "villageName",
    "houseNumber",
    "mooNumber",
    "trokSoiName",
    "streetName",
    "thambolCode",
    "thambolName",
    "amphurCode",
    "amphurName",
    "provinceCode",
    "provinceName",
    "postcode",
    "telNumber",
    "emailAddress"
})
public class Address {

    @XmlElement(name = "HouseIdNumber")
    protected String houseIdNumber;
    @XmlElement(name = "BuildingName")
    protected String buildingName;
    @XmlElement(name = "RoomNumber")
    protected String roomNumber;
    @XmlElement(name = "FloorNumber")
    protected String floorNumber;
    @XmlElement(name = "VillageName")
    protected String villageName;
    @XmlElement(name = "HouseNumber")
    protected String houseNumber;
    @XmlElement(name = "MooNumber")
    protected String mooNumber;
    @XmlElement(name = "TrokSoiName")
    protected String trokSoiName;
    @XmlElement(name = "StreetName")
    protected String streetName;
    @XmlElement(name = "ThambolCode", required = true)
    protected String thambolCode;
    @XmlElement(name = "ThambolName", required = true)
    protected String thambolName;
    @XmlElement(name = "AmphurCode", required = true)
    protected String amphurCode;
    @XmlElement(name = "AmphurName", required = true)
    protected String amphurName;
    @XmlElement(name = "ProvinceCode", required = true)
    protected String provinceCode;
    @XmlElement(name = "ProvinceName", required = true)
    protected String provinceName;
    @XmlElement(name = "Postcode")
    protected String postcode;
    @XmlElement(name = "TelNumber")
    protected String telNumber;
    @XmlElement(name = "EmailAddress")
    protected String emailAddress;

    /**
     * Gets the value of the houseIdNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseIdNumber() {
        return houseIdNumber;
    }

    /**
     * Sets the value of the houseIdNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseIdNumber(String value) {
        this.houseIdNumber = value;
    }

    /**
     * Gets the value of the buildingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * Sets the value of the buildingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildingName(String value) {
        this.buildingName = value;
    }

    /**
     * Gets the value of the roomNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * Sets the value of the roomNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomNumber(String value) {
        this.roomNumber = value;
    }

    /**
     * Gets the value of the floorNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFloorNumber() {
        return floorNumber;
    }

    /**
     * Sets the value of the floorNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFloorNumber(String value) {
        this.floorNumber = value;
    }

    /**
     * Gets the value of the villageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVillageName() {
        return villageName;
    }

    /**
     * Sets the value of the villageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVillageName(String value) {
        this.villageName = value;
    }

    /**
     * Gets the value of the houseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * Sets the value of the houseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseNumber(String value) {
        this.houseNumber = value;
    }

    /**
     * Gets the value of the mooNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMooNumber() {
        return mooNumber;
    }

    /**
     * Sets the value of the mooNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMooNumber(String value) {
        this.mooNumber = value;
    }

    /**
     * Gets the value of the trokSoiName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrokSoiName() {
        return trokSoiName;
    }

    /**
     * Sets the value of the trokSoiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrokSoiName(String value) {
        this.trokSoiName = value;
    }

    /**
     * Gets the value of the streetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * Sets the value of the streetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetName(String value) {
        this.streetName = value;
    }

    /**
     * Gets the value of the thambolCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThambolCode() {
        return thambolCode;
    }

    /**
     * Sets the value of the thambolCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThambolCode(String value) {
        this.thambolCode = value;
    }

    /**
     * Gets the value of the thambolName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThambolName() {
        return thambolName;
    }

    /**
     * Sets the value of the thambolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThambolName(String value) {
        this.thambolName = value;
    }

    /**
     * Gets the value of the amphurCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmphurCode() {
        return amphurCode;
    }

    /**
     * Sets the value of the amphurCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmphurCode(String value) {
        this.amphurCode = value;
    }

    /**
     * Gets the value of the amphurName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmphurName() {
        return amphurName;
    }

    /**
     * Sets the value of the amphurName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmphurName(String value) {
        this.amphurName = value;
    }

    /**
     * Gets the value of the provinceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * Sets the value of the provinceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvinceCode(String value) {
        this.provinceCode = value;
    }

    /**
     * Gets the value of the provinceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * Sets the value of the provinceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvinceName(String value) {
        this.provinceName = value;
    }

    /**
     * Gets the value of the postcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * Sets the value of the postcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostcode(String value) {
        this.postcode = value;
    }

    /**
     * Gets the value of the telNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelNumber() {
        return telNumber;
    }

    /**
     * Sets the value of the telNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelNumber(String value) {
        this.telNumber = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

}
