//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.22 at 05:51:32 PM ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for alcoholTaxForm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="alcoholTaxForm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="licenseNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productTaxList" type="{http://www.excise.go.th/xsd/barcode}productTax" maxOccurs="unbounded"/>
 *         &lt;element name="alcoholTaxFormSummary" type="{http://www.excise.go.th/xsd/barcode}alcoholTaxFormSummary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "alcoholTaxForm", propOrder = {
    "licenseNo",
    "productTaxList",
    "alcoholTaxFormSummary"
})
public class AlcoholTaxForm {

    @XmlElement(required = true)
    protected String licenseNo;
    @XmlElement(required = true)
    protected List<ProductTax> productTaxList;
    @XmlElement(required = true)
    protected AlcoholTaxFormSummary alcoholTaxFormSummary;

    /**
     * Gets the value of the licenseNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseNo() {
        return licenseNo;
    }

    /**
     * Sets the value of the licenseNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseNo(String value) {
        this.licenseNo = value;
    }

    /**
     * Gets the value of the productTaxList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productTaxList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductTaxList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductTax }
     * 
     * 
     */
    public List<ProductTax> getProductTaxList() {
        if (productTaxList == null) {
            productTaxList = new ArrayList<ProductTax>();
        }
        return this.productTaxList;
    }

    /**
     * Gets the value of the alcoholTaxFormSummary property.
     * 
     * @return
     *     possible object is
     *     {@link AlcoholTaxFormSummary }
     *     
     */
    public AlcoholTaxFormSummary getAlcoholTaxFormSummary() {
        return alcoholTaxFormSummary;
    }

    /**
     * Sets the value of the alcoholTaxFormSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlcoholTaxFormSummary }
     *     
     */
    public void setAlcoholTaxFormSummary(AlcoholTaxFormSummary value) {
        this.alcoholTaxFormSummary = value;
    }

}
