//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.05 at 09:14:13 PM ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubmitOnlineHeader" type="{http://www.excise.go.th/xsd/barcode}SubmitOnlineHeader"/>
 *         &lt;element name="SR12011Info" type="{http://www.excise.go.th/xsd/barcode}SR12011Info"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "submitOnlineHeader",
    "sr12011Info"
})
@XmlRootElement(name = "EbarcodeSubmitOnlineRequest")
public class EbarcodeSubmitOnlineRequest {

    @XmlElement(name = "SubmitOnlineHeader", required = true)
    protected SubmitOnlineHeader submitOnlineHeader;
    @XmlElement(name = "SR12011Info", required = true)
    protected SR12011Info sr12011Info;

    /**
     * Gets the value of the submitOnlineHeader property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitOnlineHeader }
     *     
     */
    public SubmitOnlineHeader getSubmitOnlineHeader() {
        return submitOnlineHeader;
    }

    /**
     * Sets the value of the submitOnlineHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitOnlineHeader }
     *     
     */
    public void setSubmitOnlineHeader(SubmitOnlineHeader value) {
        this.submitOnlineHeader = value;
    }

    /**
     * Gets the value of the sr12011Info property.
     * 
     * @return
     *     possible object is
     *     {@link SR12011Info }
     *     
     */
    public SR12011Info getSR12011Info() {
        return sr12011Info;
    }

    /**
     * Sets the value of the sr12011Info property.
     * 
     * @param value
     *     allowed object is
     *     {@link SR12011Info }
     *     
     */
    public void setSR12011Info(SR12011Info value) {
        this.sr12011Info = value;
    }

}
