//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2558.08.21 at 01:52:57 หลังเที่ยง ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SyncMasterDataStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SyncMasterDataDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Company" type="{http://www.excise.go.th/xsd/barcode}Company" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "syncMasterDataStatus",
    "syncMasterDataDesc",
    "company"
})
@XmlRootElement(name = "EbarcodeSyncMasterDataResponse")
public class EbarcodeSyncMasterDataResponse {

    @XmlElement(name = "SyncMasterDataStatus", required = true)
    protected String syncMasterDataStatus;
    @XmlElement(name = "SyncMasterDataDesc", required = true)
    protected String syncMasterDataDesc;
    @XmlElement(name = "Company")
    protected Company company;

    /**
     * Gets the value of the syncMasterDataStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyncMasterDataStatus() {
        return syncMasterDataStatus;
    }

    /**
     * Sets the value of the syncMasterDataStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyncMasterDataStatus(String value) {
        this.syncMasterDataStatus = value;
    }

    /**
     * Gets the value of the syncMasterDataDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyncMasterDataDesc() {
        return syncMasterDataDesc;
    }

    /**
     * Sets the value of the syncMasterDataDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyncMasterDataDesc(String value) {
        this.syncMasterDataDesc = value;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link Company }
     *     
     */
    public Company getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link Company }
     *     
     */
    public void setCompany(Company value) {
        this.company = value;
    }

}
