//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2558.08.21 at 01:52:57 หลังเที่ยง ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InternetUser" type="{http://www.excise.go.th/xsd/barcode}InternetUser"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "internetUser"
})
@XmlRootElement(name = "EbarcodeSyncMasterDataRequest")
public class EbarcodeSyncMasterDataRequest {

    @XmlElement(name = "InternetUser", required = true)
    protected InternetUser internetUser;

    /**
     * Gets the value of the internetUser property.
     * 
     * @return
     *     possible object is
     *     {@link InternetUser }
     *     
     */
    public InternetUser getInternetUser() {
        return internetUser;
    }

    /**
     * Sets the value of the internetUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternetUser }
     *     
     */
    public void setInternetUser(InternetUser value) {
        this.internetUser = value;
    }

}
