//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.26 at 09:32:28 PM ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the th.go.excise.edbarcode.ws.provider.oxm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: th.go.excise.edbarcode.ws.provider.oxm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EbarcodeSubmitOnlineRequest }
     * 
     */
    public EbarcodeSubmitOnlineRequest createEbarcodeSubmitOnlineRequest() {
        return new EbarcodeSubmitOnlineRequest();
    }

    /**
     * Create an instance of {@link SR12011 }
     * 
     */
    public SR12011 createSR12011() {
        return new SR12011();
    }

    /**
     * Create an instance of {@link EbarcodeSyncMasterDataResponse }
     * 
     */
    public EbarcodeSyncMasterDataResponse createEbarcodeSyncMasterDataResponse() {
        return new EbarcodeSyncMasterDataResponse();
    }

    /**
     * Create an instance of {@link Company }
     * 
     */
    public Company createCompany() {
        return new Company();
    }

    /**
     * Create an instance of {@link EbarcodeSyncMasterDataRequest }
     * 
     */
    public EbarcodeSyncMasterDataRequest createEbarcodeSyncMasterDataRequest() {
        return new EbarcodeSyncMasterDataRequest();
    }

    /**
     * Create an instance of {@link InternetUser }
     * 
     */
    public InternetUser createInternetUser() {
        return new InternetUser();
    }

    /**
     * Create an instance of {@link EbarcodeSubmitOnlineResponse }
     * 
     */
    public EbarcodeSubmitOnlineResponse createEbarcodeSubmitOnlineResponse() {
        return new EbarcodeSubmitOnlineResponse();
    }

    /**
     * Create an instance of {@link LicenseList }
     * 
     */
    public LicenseList createLicenseList() {
        return new LicenseList();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link GoodsList }
     * 
     */
    public GoodsList createGoodsList() {
        return new GoodsList();
    }

    /**
     * Create an instance of {@link Goods }
     * 
     */
    public Goods createGoods() {
        return new Goods();
    }

    /**
     * Create an instance of {@link LicenseInfo }
     * 
     */
    public LicenseInfo createLicenseInfo() {
        return new LicenseInfo();
    }

    /**
     * Create an instance of {@link TaxpayerDetail }
     * 
     */
    public TaxpayerDetail createTaxpayerDetail() {
        return new TaxpayerDetail();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link TaxpayerList }
     * 
     */
    public TaxpayerList createTaxpayerList() {
        return new TaxpayerList();
    }

}
