//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.09 at 10:52:27 AM ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the th.go.excise.edbarcode.ws.provider.oxm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: th.go.excise.edbarcode.ws.provider.oxm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EbarcodeSyncMasterDataResponse }
     * 
     */
    public EbarcodeSyncMasterDataResponse createEbarcodeSyncMasterDataResponse() {
        return new EbarcodeSyncMasterDataResponse();
    }

    /**
     * Create an instance of {@link EbarcodeSyncMasterDataRequest }
     * 
     */
    public EbarcodeSyncMasterDataRequest createEbarcodeSyncMasterDataRequest() {
        return new EbarcodeSyncMasterDataRequest();
    }

    /**
     * Create an instance of {@link FundListInfo }
     * 
     */
    public FundListInfo createFundListInfo() {
        return new FundListInfo();
    }

    /**
     * Create an instance of {@link GoodsListInfo }
     * 
     */
    public GoodsListInfo createGoodsListInfo() {
        return new GoodsListInfo();
    }

    /**
     * Create an instance of {@link GoodsEntryInfo }
     * 
     */
    public GoodsEntryInfo createGoodsEntryInfo() {
        return new GoodsEntryInfo();
    }

    /**
     * Create an instance of {@link SubmitOnlineHeader }
     * 
     */
    public SubmitOnlineHeader createSubmitOnlineHeader() {
        return new SubmitOnlineHeader();
    }

    /**
     * Create an instance of {@link GoodsList }
     * 
     */
    public GoodsList createGoodsList() {
        return new GoodsList();
    }

    /**
     * Create an instance of {@link LicenseInfo }
     * 
     */
    public LicenseInfo createLicenseInfo() {
        return new LicenseInfo();
    }

    /**
     * Create an instance of {@link SummaryInfo }
     * 
     */
    public SummaryInfo createSummaryInfo() {
        return new SummaryInfo();
    }

    /**
     * Create an instance of {@link InternetUser }
     * 
     */
    public InternetUser createInternetUser() {
        return new InternetUser();
    }

    /**
     * Create an instance of {@link EbarcodeSubmitOnlineRequest }
     * 
     */
    public EbarcodeSubmitOnlineRequest createEbarcodeSubmitOnlineRequest() {
        return new EbarcodeSubmitOnlineRequest();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link TaxpayerInfo }
     * 
     */
    public TaxpayerInfo createTaxpayerInfo() {
        return new TaxpayerInfo();
    }

    /**
     * Create an instance of {@link EbarcodeSubmitOnlineResponse }
     * 
     */
    public EbarcodeSubmitOnlineResponse createEbarcodeSubmitOnlineResponse() {
        return new EbarcodeSubmitOnlineResponse();
    }

    /**
     * Create an instance of {@link TaxpayerList }
     * 
     */
    public TaxpayerList createTaxpayerList() {
        return new TaxpayerList();
    }

    /**
     * Create an instance of {@link TaxpayerAddressInfo }
     * 
     */
    public TaxpayerAddressInfo createTaxpayerAddressInfo() {
        return new TaxpayerAddressInfo();
    }

    /**
     * Create an instance of {@link Company }
     * 
     */
    public Company createCompany() {
        return new Company();
    }

    /**
     * Create an instance of {@link TaxpayerDetail }
     * 
     */
    public TaxpayerDetail createTaxpayerDetail() {
        return new TaxpayerDetail();
    }

    /**
     * Create an instance of {@link FundEntryInfo }
     * 
     */
    public FundEntryInfo createFundEntryInfo() {
        return new FundEntryInfo();
    }

    /**
     * Create an instance of {@link Goods }
     * 
     */
    public Goods createGoods() {
        return new Goods();
    }

    /**
     * Create an instance of {@link LicenseList }
     * 
     */
    public LicenseList createLicenseList() {
        return new LicenseList();
    }

    /**
     * Create an instance of {@link SR12011Info }
     * 
     */
    public SR12011Info createSR12011Info() {
        return new SR12011Info();
    }

}
