//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.22 at 05:51:32 PM ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alcoholTaxForm" type="{http://www.excise.go.th/xsd/barcode}alcoholTaxForm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "alcoholTaxForm"
})
@XmlRootElement(name = "submitOnlineRequest")
public class SubmitOnlineRequest {

    @XmlElement(required = true)
    protected AlcoholTaxForm alcoholTaxForm;

    /**
     * Gets the value of the alcoholTaxForm property.
     * 
     * @return
     *     possible object is
     *     {@link AlcoholTaxForm }
     *     
     */
    public AlcoholTaxForm getAlcoholTaxForm() {
        return alcoholTaxForm;
    }

    /**
     * Sets the value of the alcoholTaxForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlcoholTaxForm }
     *     
     */
    public void setAlcoholTaxForm(AlcoholTaxForm value) {
        this.alcoholTaxForm = value;
    }

}
