//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.05 at 09:14:13 PM ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubmitOnlineHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubmitOnlineHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RegistratronId" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="CusId" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="CompanyId" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TaxpayerId" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ExciseOfficeId" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="InternetUniqueId" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="IpAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubmissionEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubmitOnlineHeader", propOrder = {
    "registratronId",
    "cusId",
    "companyId",
    "taxpayerId",
    "exciseOfficeId",
    "internetUniqueId",
    "ipAddress",
    "submissionEmail"
})
public class SubmitOnlineHeader {

    @XmlElement(name = "RegistratronId")
    protected double registratronId;
    @XmlElement(name = "CusId")
    protected double cusId;
    @XmlElement(name = "CompanyId")
    protected double companyId;
    @XmlElement(name = "TaxpayerId")
    protected double taxpayerId;
    @XmlElement(name = "ExciseOfficeId")
    protected double exciseOfficeId;
    @XmlElement(name = "InternetUniqueId")
    protected double internetUniqueId;
    @XmlElement(name = "IpAddress", required = true)
    protected String ipAddress;
    @XmlElement(name = "SubmissionEmail")
    protected String submissionEmail;

    /**
     * Gets the value of the registratronId property.
     * 
     */
    public double getRegistratronId() {
        return registratronId;
    }

    /**
     * Sets the value of the registratronId property.
     * 
     */
    public void setRegistratronId(double value) {
        this.registratronId = value;
    }

    /**
     * Gets the value of the cusId property.
     * 
     */
    public double getCusId() {
        return cusId;
    }

    /**
     * Sets the value of the cusId property.
     * 
     */
    public void setCusId(double value) {
        this.cusId = value;
    }

    /**
     * Gets the value of the companyId property.
     * 
     */
    public double getCompanyId() {
        return companyId;
    }

    /**
     * Sets the value of the companyId property.
     * 
     */
    public void setCompanyId(double value) {
        this.companyId = value;
    }

    /**
     * Gets the value of the taxpayerId property.
     * 
     */
    public double getTaxpayerId() {
        return taxpayerId;
    }

    /**
     * Sets the value of the taxpayerId property.
     * 
     */
    public void setTaxpayerId(double value) {
        this.taxpayerId = value;
    }

    /**
     * Gets the value of the exciseOfficeId property.
     * 
     */
    public double getExciseOfficeId() {
        return exciseOfficeId;
    }

    /**
     * Sets the value of the exciseOfficeId property.
     * 
     */
    public void setExciseOfficeId(double value) {
        this.exciseOfficeId = value;
    }

    /**
     * Gets the value of the internetUniqueId property.
     * 
     */
    public double getInternetUniqueId() {
        return internetUniqueId;
    }

    /**
     * Sets the value of the internetUniqueId property.
     * 
     */
    public void setInternetUniqueId(double value) {
        this.internetUniqueId = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpAddress(String value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the submissionEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmissionEmail() {
        return submissionEmail;
    }

    /**
     * Sets the value of the submissionEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmissionEmail(String value) {
        this.submissionEmail = value;
    }

}
