//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 08:34:45 PM ICT 
//


package th.go.excise.edbarcode.ws.client.sta.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Body complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Body">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Error" type="{http://www.example.org/StaBacSchema}Error" minOccurs="0"/>
 *         &lt;element name="InternetUser" type="{http://www.example.org/StaBacSchema}InternetUser" minOccurs="0"/>
 *         &lt;element name="Company" type="{http://www.example.org/StaBacSchema}Company" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Body", propOrder = {

})
public class Body {

    @XmlElement(name = "Error")
    protected Error error;
    @XmlElement(name = "InternetUser")
    protected InternetUser internetUser;
    @XmlElement(name = "Company")
    protected Company company;

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link Error }
     *     
     */
    public Error getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link Error }
     *     
     */
    public void setError(Error value) {
        this.error = value;
    }

    /**
     * Gets the value of the internetUser property.
     * 
     * @return
     *     possible object is
     *     {@link InternetUser }
     *     
     */
    public InternetUser getInternetUser() {
        return internetUser;
    }

    /**
     * Sets the value of the internetUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternetUser }
     *     
     */
    public void setInternetUser(InternetUser value) {
        this.internetUser = value;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link Company }
     *     
     */
    public Company getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link Company }
     *     
     */
    public void setCompany(Company value) {
        this.company = value;
    }

}
