//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 08:34:45 PM ICT 
//


package th.go.excise.edbarcode.ws.client.sta.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Company complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Company">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="InternetUniqueId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CusId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyUserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyTitleCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyTitleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyBranchCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ExciseOfficeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyUserPwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyAddress" type="{http://www.example.org/StaBacSchema}Address"/>
 *         &lt;element name="TaxpayerList" type="{http://www.example.org/StaBacSchema}TaxpayerList" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Company", propOrder = {

})
public class Company {

    @XmlElement(name = "InternetUniqueId", required = true)
    protected String internetUniqueId;
    @XmlElement(name = "CusId", required = true)
    protected String cusId;
    @XmlElement(name = "CompanyId", required = true)
    protected String companyId;
    @XmlElement(name = "CompanyUserId", required = true)
    protected String companyUserId;
    @XmlElement(name = "CompanyTitleCode", required = true)
    protected String companyTitleCode;
    @XmlElement(name = "CompanyTitleName", required = true)
    protected String companyTitleName;
    @XmlElement(name = "CompanyName", required = true)
    protected String companyName;
    @XmlElement(name = "CompanyBranchCode", required = true)
    protected String companyBranchCode;
    @XmlElement(name = "ExciseOfficeId", required = true)
    protected String exciseOfficeId;
    @XmlElement(name = "CompanyUserPwd", required = true)
    protected String companyUserPwd;
    @XmlElement(name = "CompanyAddress", required = true)
    protected Address companyAddress;
    @XmlElement(name = "TaxpayerList")
    protected TaxpayerList taxpayerList;

    /**
     * Gets the value of the internetUniqueId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternetUniqueId() {
        return internetUniqueId;
    }

    /**
     * Sets the value of the internetUniqueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternetUniqueId(String value) {
        this.internetUniqueId = value;
    }

    /**
     * Gets the value of the cusId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCusId() {
        return cusId;
    }

    /**
     * Sets the value of the cusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCusId(String value) {
        this.cusId = value;
    }

    /**
     * Gets the value of the companyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * Sets the value of the companyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyId(String value) {
        this.companyId = value;
    }

    /**
     * Gets the value of the companyUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyUserId() {
        return companyUserId;
    }

    /**
     * Sets the value of the companyUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyUserId(String value) {
        this.companyUserId = value;
    }

    /**
     * Gets the value of the companyTitleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyTitleCode() {
        return companyTitleCode;
    }

    /**
     * Sets the value of the companyTitleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyTitleCode(String value) {
        this.companyTitleCode = value;
    }

    /**
     * Gets the value of the companyTitleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyTitleName() {
        return companyTitleName;
    }

    /**
     * Sets the value of the companyTitleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyTitleName(String value) {
        this.companyTitleName = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the companyBranchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyBranchCode() {
        return companyBranchCode;
    }

    /**
     * Sets the value of the companyBranchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyBranchCode(String value) {
        this.companyBranchCode = value;
    }

    /**
     * Gets the value of the exciseOfficeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExciseOfficeId() {
        return exciseOfficeId;
    }

    /**
     * Sets the value of the exciseOfficeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExciseOfficeId(String value) {
        this.exciseOfficeId = value;
    }

    /**
     * Gets the value of the companyUserPwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyUserPwd() {
        return companyUserPwd;
    }

    /**
     * Sets the value of the companyUserPwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyUserPwd(String value) {
        this.companyUserPwd = value;
    }

    /**
     * Gets the value of the companyAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getCompanyAddress() {
        return companyAddress;
    }

    /**
     * Sets the value of the companyAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setCompanyAddress(Address value) {
        this.companyAddress = value;
    }

    /**
     * Gets the value of the taxpayerList property.
     * 
     * @return
     *     possible object is
     *     {@link TaxpayerList }
     *     
     */
    public TaxpayerList getTaxpayerList() {
        return taxpayerList;
    }

    /**
     * Sets the value of the taxpayerList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxpayerList }
     *     
     */
    public void setTaxpayerList(TaxpayerList value) {
        this.taxpayerList = value;
    }

}
