//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 08:34:45 PM ICT 
//


package th.go.excise.edbarcode.ws.client.sta.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Goods complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Goods">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="GoodsCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GoodsDescriptionText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductTypeDescriptionText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GoodsSize" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GoodsSizeUnitDescriptionText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GoodsPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TaxRateByPriceAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TaxRateByQuantityAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="FundSSSRateAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="FundSSTRateAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Degree" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PriceFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeclarePrice" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="UnitCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GoodsUnitsDescriptionText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IncomeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SeqNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BrandName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubbrandName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ModelName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InformDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductNameEng" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RatePerLitre" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="DegreeMin" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="RateDegreeOver" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="WholesaleMin" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="RateWholesaleOver" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="RatePerLitreMax" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Goods", propOrder = {

})
public class Goods {

    @XmlElement(name = "GoodsCode", required = true)
    protected String goodsCode;
    @XmlElement(name = "GoodsDescriptionText", required = true)
    protected String goodsDescriptionText;
    @XmlElement(name = "ProductTypeCode", required = true)
    protected String productTypeCode;
    @XmlElement(name = "ProductTypeDescriptionText", required = true)
    protected String productTypeDescriptionText;
    @XmlElement(name = "GoodsSize")
    protected String goodsSize;
    @XmlElement(name = "GoodsSizeUnitDescriptionText")
    protected String goodsSizeUnitDescriptionText;
    @XmlElement(name = "GoodsPrice")
    protected double goodsPrice;
    @XmlElement(name = "TaxRateByPriceAmount")
    protected double taxRateByPriceAmount;
    @XmlElement(name = "TaxRateByQuantityAmount")
    protected double taxRateByQuantityAmount;
    @XmlElement(name = "FundSSSRateAmount")
    protected double fundSSSRateAmount;
    @XmlElement(name = "FundSSTRateAmount")
    protected double fundSSTRateAmount;
    @XmlElement(name = "Degree")
    protected String degree;
    @XmlElement(name = "PriceFlag", required = true)
    protected String priceFlag;
    @XmlElement(name = "DeclarePrice")
    protected Double declarePrice;
    @XmlElement(name = "UnitCode", required = true)
    protected String unitCode;
    @XmlElement(name = "GoodsUnitsDescriptionText", required = true)
    protected String goodsUnitsDescriptionText;
    @XmlElement(name = "IncomeCode", required = true)
    protected String incomeCode;
    @XmlElement(name = "SeqNo", required = true)
    protected String seqNo;
    @XmlElement(name = "BrandName")
    protected String brandName;
    @XmlElement(name = "SubbrandName")
    protected String subbrandName;
    @XmlElement(name = "ModelName")
    protected String modelName;
    @XmlElement(name = "InformDate")
    protected String informDate;
    @XmlElement(name = "ProductNameEng")
    protected String productNameEng;
    @XmlElement(name = "RatePerLitre")
    protected double ratePerLitre;
    @XmlElement(name = "DegreeMin")
    protected double degreeMin;
    @XmlElement(name = "RateDegreeOver")
    protected double rateDegreeOver;
    @XmlElement(name = "WholesaleMin")
    protected double wholesaleMin;
    @XmlElement(name = "RateWholesaleOver")
    protected double rateWholesaleOver;
    @XmlElement(name = "RatePerLitreMax")
    protected double ratePerLitreMax;

    /**
     * Gets the value of the goodsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodsCode() {
        return goodsCode;
    }

    /**
     * Sets the value of the goodsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsCode(String value) {
        this.goodsCode = value;
    }

    /**
     * Gets the value of the goodsDescriptionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodsDescriptionText() {
        return goodsDescriptionText;
    }

    /**
     * Sets the value of the goodsDescriptionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsDescriptionText(String value) {
        this.goodsDescriptionText = value;
    }

    /**
     * Gets the value of the productTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductTypeCode() {
        return productTypeCode;
    }

    /**
     * Sets the value of the productTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductTypeCode(String value) {
        this.productTypeCode = value;
    }

    /**
     * Gets the value of the productTypeDescriptionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductTypeDescriptionText() {
        return productTypeDescriptionText;
    }

    /**
     * Sets the value of the productTypeDescriptionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductTypeDescriptionText(String value) {
        this.productTypeDescriptionText = value;
    }

    /**
     * Gets the value of the goodsSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodsSize() {
        return goodsSize;
    }

    /**
     * Sets the value of the goodsSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsSize(String value) {
        this.goodsSize = value;
    }

    /**
     * Gets the value of the goodsSizeUnitDescriptionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodsSizeUnitDescriptionText() {
        return goodsSizeUnitDescriptionText;
    }

    /**
     * Sets the value of the goodsSizeUnitDescriptionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsSizeUnitDescriptionText(String value) {
        this.goodsSizeUnitDescriptionText = value;
    }

    /**
     * Gets the value of the goodsPrice property.
     * 
     */
    public double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * Sets the value of the goodsPrice property.
     * 
     */
    public void setGoodsPrice(double value) {
        this.goodsPrice = value;
    }

    /**
     * Gets the value of the taxRateByPriceAmount property.
     * 
     */
    public double getTaxRateByPriceAmount() {
        return taxRateByPriceAmount;
    }

    /**
     * Sets the value of the taxRateByPriceAmount property.
     * 
     */
    public void setTaxRateByPriceAmount(double value) {
        this.taxRateByPriceAmount = value;
    }

    /**
     * Gets the value of the taxRateByQuantityAmount property.
     * 
     */
    public double getTaxRateByQuantityAmount() {
        return taxRateByQuantityAmount;
    }

    /**
     * Sets the value of the taxRateByQuantityAmount property.
     * 
     */
    public void setTaxRateByQuantityAmount(double value) {
        this.taxRateByQuantityAmount = value;
    }

    /**
     * Gets the value of the fundSSSRateAmount property.
     * 
     */
    public double getFundSSSRateAmount() {
        return fundSSSRateAmount;
    }

    /**
     * Sets the value of the fundSSSRateAmount property.
     * 
     */
    public void setFundSSSRateAmount(double value) {
        this.fundSSSRateAmount = value;
    }

    /**
     * Gets the value of the fundSSTRateAmount property.
     * 
     */
    public double getFundSSTRateAmount() {
        return fundSSTRateAmount;
    }

    /**
     * Sets the value of the fundSSTRateAmount property.
     * 
     */
    public void setFundSSTRateAmount(double value) {
        this.fundSSTRateAmount = value;
    }

    /**
     * Gets the value of the degree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDegree() {
        return degree;
    }

    /**
     * Sets the value of the degree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDegree(String value) {
        this.degree = value;
    }

    /**
     * Gets the value of the priceFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceFlag() {
        return priceFlag;
    }

    /**
     * Sets the value of the priceFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceFlag(String value) {
        this.priceFlag = value;
    }

    /**
     * Gets the value of the declarePrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDeclarePrice() {
        return declarePrice;
    }

    /**
     * Sets the value of the declarePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDeclarePrice(Double value) {
        this.declarePrice = value;
    }

    /**
     * Gets the value of the unitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * Sets the value of the unitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitCode(String value) {
        this.unitCode = value;
    }

    /**
     * Gets the value of the goodsUnitsDescriptionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodsUnitsDescriptionText() {
        return goodsUnitsDescriptionText;
    }

    /**
     * Sets the value of the goodsUnitsDescriptionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsUnitsDescriptionText(String value) {
        this.goodsUnitsDescriptionText = value;
    }

    /**
     * Gets the value of the incomeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncomeCode() {
        return incomeCode;
    }

    /**
     * Sets the value of the incomeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncomeCode(String value) {
        this.incomeCode = value;
    }

    /**
     * Gets the value of the seqNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqNo(String value) {
        this.seqNo = value;
    }

    /**
     * Gets the value of the brandName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * Sets the value of the brandName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrandName(String value) {
        this.brandName = value;
    }

    /**
     * Gets the value of the subbrandName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubbrandName() {
        return subbrandName;
    }

    /**
     * Sets the value of the subbrandName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubbrandName(String value) {
        this.subbrandName = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the informDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformDate() {
        return informDate;
    }

    /**
     * Sets the value of the informDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformDate(String value) {
        this.informDate = value;
    }

    /**
     * Gets the value of the productNameEng property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductNameEng() {
        return productNameEng;
    }

    /**
     * Sets the value of the productNameEng property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductNameEng(String value) {
        this.productNameEng = value;
    }

    /**
     * Gets the value of the ratePerLitre property.
     * 
     */
    public double getRatePerLitre() {
        return ratePerLitre;
    }

    /**
     * Sets the value of the ratePerLitre property.
     * 
     */
    public void setRatePerLitre(double value) {
        this.ratePerLitre = value;
    }

    /**
     * Gets the value of the degreeMin property.
     * 
     */
    public double getDegreeMin() {
        return degreeMin;
    }

    /**
     * Sets the value of the degreeMin property.
     * 
     */
    public void setDegreeMin(double value) {
        this.degreeMin = value;
    }

    /**
     * Gets the value of the rateDegreeOver property.
     * 
     */
    public double getRateDegreeOver() {
        return rateDegreeOver;
    }

    /**
     * Sets the value of the rateDegreeOver property.
     * 
     */
    public void setRateDegreeOver(double value) {
        this.rateDegreeOver = value;
    }

    /**
     * Gets the value of the wholesaleMin property.
     * 
     */
    public double getWholesaleMin() {
        return wholesaleMin;
    }

    /**
     * Sets the value of the wholesaleMin property.
     * 
     */
    public void setWholesaleMin(double value) {
        this.wholesaleMin = value;
    }

    /**
     * Gets the value of the rateWholesaleOver property.
     * 
     */
    public double getRateWholesaleOver() {
        return rateWholesaleOver;
    }

    /**
     * Sets the value of the rateWholesaleOver property.
     * 
     */
    public void setRateWholesaleOver(double value) {
        this.rateWholesaleOver = value;
    }

    /**
     * Gets the value of the ratePerLitreMax property.
     * 
     */
    public double getRatePerLitreMax() {
        return ratePerLitreMax;
    }

    /**
     * Sets the value of the ratePerLitreMax property.
     * 
     */
    public void setRatePerLitreMax(double value) {
        this.ratePerLitreMax = value;
    }

}
