//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.11 at 02:03:07 PM ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SendTobackendStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SendTobackendDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendTobackendStatus",
    "sendTobackendDesc"
})
@XmlRootElement(name = "EbarcodeSendToBackendResponse")
public class EbarcodeSendToBackendResponse {

    @XmlElement(name = "SendTobackendStatus", required = true)
    protected String sendTobackendStatus;
    @XmlElement(name = "SendTobackendDesc", required = true)
    protected String sendTobackendDesc;

    /**
     * Gets the value of the sendTobackendStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendTobackendStatus() {
        return sendTobackendStatus;
    }

    /**
     * Sets the value of the sendTobackendStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendTobackendStatus(String value) {
        this.sendTobackendStatus = value;
    }

    /**
     * Gets the value of the sendTobackendDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendTobackendDesc() {
        return sendTobackendDesc;
    }

    /**
     * Sets the value of the sendTobackendDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendTobackendDesc(String value) {
        this.sendTobackendDesc = value;
    }

}
