//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.20 at 08:24:20 PM ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataInformation" type="{http://www.excise.go.th/xsd/barcode}DataInformation"/>
 *         &lt;element name="BinaryInformation" type="{http://www.excise.go.th/xsd/barcode}BinaryInformation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataInformation",
    "binaryInformation"
})
@XmlRootElement(name = "EbarcodeSendFormSR12011Request")
public class EbarcodeSendFormSR12011Request {

    @XmlElement(name = "DataInformation", required = true)
    protected DataInformation dataInformation;
    @XmlElement(name = "BinaryInformation", required = true)
    protected BinaryInformation binaryInformation;

    /**
     * Gets the value of the dataInformation property.
     * 
     * @return
     *     possible object is
     *     {@link DataInformation }
     *     
     */
    public DataInformation getDataInformation() {
        return dataInformation;
    }

    /**
     * Sets the value of the dataInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataInformation }
     *     
     */
    public void setDataInformation(DataInformation value) {
        this.dataInformation = value;
    }

    /**
     * Gets the value of the binaryInformation property.
     * 
     * @return
     *     possible object is
     *     {@link BinaryInformation }
     *     
     */
    public BinaryInformation getBinaryInformation() {
        return binaryInformation;
    }

    /**
     * Sets the value of the binaryInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BinaryInformation }
     *     
     */
    public void setBinaryInformation(BinaryInformation value) {
        this.binaryInformation = value;
    }

}
