//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.26 at 09:32:28 PM ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SR12011" type="{http://www.excise.go.th/xsd/barcode}SR12011"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sr12011"
})
@XmlRootElement(name = "EbarcodeSubmitOnlineRequest")
public class EbarcodeSubmitOnlineRequest {

    @XmlElement(name = "SR12011", required = true)
    protected SR12011 sr12011;

    /**
     * Gets the value of the sr12011 property.
     * 
     * @return
     *     possible object is
     *     {@link SR12011 }
     *     
     */
    public SR12011 getSR12011() {
        return sr12011;
    }

    /**
     * Sets the value of the sr12011 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SR12011 }
     *     
     */
    public void setSR12011(SR12011 value) {
        this.sr12011 = value;
    }

}
