//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.21 at 03:59:47 PM ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SendFormSR12011Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SendFormSR12011Desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendFormSR12011Status",
    "sendFormSR12011Desc"
})
@XmlRootElement(name = "EbarcodeSendFormSR12011Response")
public class EbarcodeSendFormSR12011Response {

    @XmlElement(name = "SendFormSR12011Status", required = true)
    protected String sendFormSR12011Status;
    @XmlElement(name = "SendFormSR12011Desc", required = true)
    protected String sendFormSR12011Desc;

    /**
     * Gets the value of the sendFormSR12011Status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendFormSR12011Status() {
        return sendFormSR12011Status;
    }

    /**
     * Sets the value of the sendFormSR12011Status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendFormSR12011Status(String value) {
        this.sendFormSR12011Status = value;
    }

    /**
     * Gets the value of the sendFormSR12011Desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendFormSR12011Desc() {
        return sendFormSR12011Desc;
    }

    /**
     * Sets the value of the sendFormSR12011Desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendFormSR12011Desc(String value) {
        this.sendFormSR12011Desc = value;
    }

}
