//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.05 at 09:56:46 PM ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GoodsEntryInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GoodsEntryInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CategoryCode1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CategoryCode2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CategoryCode3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CategoryCode4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CategoryCode5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UnitCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RateFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TaxQuantity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TaxQuantityNumber" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TaxQuantityPerUnit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TaxValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="PriceFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InformPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="DeclarePrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="GoodsNum" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="GoodsValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TaxAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="SeqNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductTypeDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GoodsDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Degree" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GoodsSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GoodsPiece" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="GoodsQuantity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TaxByValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TaxByQuantity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TaxByQuantityOver" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TaxByQuantityWithOver" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="NetTaxByValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="NetTaxByQuantity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GoodsEntryInfo", propOrder = {
    "productCode",
    "categoryCode1",
    "categoryCode2",
    "categoryCode3",
    "categoryCode4",
    "categoryCode5",
    "unitCode",
    "rateFlag",
    "taxQuantity",
    "taxQuantityNumber",
    "taxQuantityPerUnit",
    "taxValue",
    "priceFlag",
    "informPrice",
    "declarePrice",
    "unitPrice",
    "goodsNum",
    "goodsValue",
    "taxAmount",
    "seqNo",
    "productTypeDesc",
    "goodsDesc",
    "degree",
    "goodsSize",
    "goodsPiece",
    "goodsQuantity",
    "taxByValue",
    "taxByQuantity",
    "taxByQuantityOver",
    "taxByQuantityWithOver",
    "netTaxByValue",
    "netTaxByQuantity"
})
public class GoodsEntryInfo {

    @XmlElement(name = "ProductCode", required = true)
    protected String productCode;
    @XmlElement(name = "CategoryCode1", required = true)
    protected String categoryCode1;
    @XmlElement(name = "CategoryCode2", required = true)
    protected String categoryCode2;
    @XmlElement(name = "CategoryCode3", required = true)
    protected String categoryCode3;
    @XmlElement(name = "CategoryCode4", required = true)
    protected String categoryCode4;
    @XmlElement(name = "CategoryCode5", required = true)
    protected String categoryCode5;
    @XmlElement(name = "UnitCode", required = true)
    protected String unitCode;
    @XmlElement(name = "RateFlag", required = true)
    protected String rateFlag;
    @XmlElement(name = "TaxQuantity", required = true)
    protected BigDecimal taxQuantity;
    @XmlElement(name = "TaxQuantityNumber", required = true)
    protected BigDecimal taxQuantityNumber;
    @XmlElement(name = "TaxQuantityPerUnit", required = true)
    protected BigDecimal taxQuantityPerUnit;
    @XmlElement(name = "TaxValue", required = true)
    protected BigDecimal taxValue;
    @XmlElement(name = "PriceFlag", required = true)
    protected String priceFlag;
    @XmlElement(name = "InformPrice", required = true)
    protected BigDecimal informPrice;
    @XmlElement(name = "DeclarePrice", required = true)
    protected BigDecimal declarePrice;
    @XmlElement(name = "UnitPrice", required = true)
    protected BigDecimal unitPrice;
    @XmlElement(name = "GoodsNum", required = true)
    protected BigDecimal goodsNum;
    @XmlElement(name = "GoodsValue", required = true)
    protected BigDecimal goodsValue;
    @XmlElement(name = "TaxAmount", required = true)
    protected BigDecimal taxAmount;
    @XmlElement(name = "SeqNo", required = true)
    protected String seqNo;
    @XmlElement(name = "ProductTypeDesc", required = true)
    protected String productTypeDesc;
    @XmlElement(name = "GoodsDesc", required = true)
    protected String goodsDesc;
    @XmlElement(name = "Degree", required = true)
    protected String degree;
    @XmlElement(name = "GoodsSize", required = true)
    protected String goodsSize;
    @XmlElement(name = "GoodsPiece", required = true)
    protected BigDecimal goodsPiece;
    @XmlElement(name = "GoodsQuantity", required = true)
    protected BigDecimal goodsQuantity;
    @XmlElement(name = "TaxByValue", required = true)
    protected BigDecimal taxByValue;
    @XmlElement(name = "TaxByQuantity", required = true)
    protected BigDecimal taxByQuantity;
    @XmlElement(name = "TaxByQuantityOver", required = true)
    protected BigDecimal taxByQuantityOver;
    @XmlElement(name = "TaxByQuantityWithOver", required = true)
    protected BigDecimal taxByQuantityWithOver;
    @XmlElement(name = "NetTaxByValue", required = true)
    protected BigDecimal netTaxByValue;
    @XmlElement(name = "NetTaxByQuantity", required = true)
    protected BigDecimal netTaxByQuantity;

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the categoryCode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode1() {
        return categoryCode1;
    }

    /**
     * Sets the value of the categoryCode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode1(String value) {
        this.categoryCode1 = value;
    }

    /**
     * Gets the value of the categoryCode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode2() {
        return categoryCode2;
    }

    /**
     * Sets the value of the categoryCode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode2(String value) {
        this.categoryCode2 = value;
    }

    /**
     * Gets the value of the categoryCode3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode3() {
        return categoryCode3;
    }

    /**
     * Sets the value of the categoryCode3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode3(String value) {
        this.categoryCode3 = value;
    }

    /**
     * Gets the value of the categoryCode4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode4() {
        return categoryCode4;
    }

    /**
     * Sets the value of the categoryCode4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode4(String value) {
        this.categoryCode4 = value;
    }

    /**
     * Gets the value of the categoryCode5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode5() {
        return categoryCode5;
    }

    /**
     * Sets the value of the categoryCode5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode5(String value) {
        this.categoryCode5 = value;
    }

    /**
     * Gets the value of the unitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * Sets the value of the unitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitCode(String value) {
        this.unitCode = value;
    }

    /**
     * Gets the value of the rateFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateFlag() {
        return rateFlag;
    }

    /**
     * Sets the value of the rateFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateFlag(String value) {
        this.rateFlag = value;
    }

    /**
     * Gets the value of the taxQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxQuantity() {
        return taxQuantity;
    }

    /**
     * Sets the value of the taxQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxQuantity(BigDecimal value) {
        this.taxQuantity = value;
    }

    /**
     * Gets the value of the taxQuantityNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxQuantityNumber() {
        return taxQuantityNumber;
    }

    /**
     * Sets the value of the taxQuantityNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxQuantityNumber(BigDecimal value) {
        this.taxQuantityNumber = value;
    }

    /**
     * Gets the value of the taxQuantityPerUnit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxQuantityPerUnit() {
        return taxQuantityPerUnit;
    }

    /**
     * Sets the value of the taxQuantityPerUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxQuantityPerUnit(BigDecimal value) {
        this.taxQuantityPerUnit = value;
    }

    /**
     * Gets the value of the taxValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxValue() {
        return taxValue;
    }

    /**
     * Sets the value of the taxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxValue(BigDecimal value) {
        this.taxValue = value;
    }

    /**
     * Gets the value of the priceFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceFlag() {
        return priceFlag;
    }

    /**
     * Sets the value of the priceFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceFlag(String value) {
        this.priceFlag = value;
    }

    /**
     * Gets the value of the informPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInformPrice() {
        return informPrice;
    }

    /**
     * Sets the value of the informPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInformPrice(BigDecimal value) {
        this.informPrice = value;
    }

    /**
     * Gets the value of the declarePrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDeclarePrice() {
        return declarePrice;
    }

    /**
     * Sets the value of the declarePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDeclarePrice(BigDecimal value) {
        this.declarePrice = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitPrice(BigDecimal value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the goodsNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGoodsNum() {
        return goodsNum;
    }

    /**
     * Sets the value of the goodsNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGoodsNum(BigDecimal value) {
        this.goodsNum = value;
    }

    /**
     * Gets the value of the goodsValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGoodsValue() {
        return goodsValue;
    }

    /**
     * Sets the value of the goodsValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGoodsValue(BigDecimal value) {
        this.goodsValue = value;
    }

    /**
     * Gets the value of the taxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxAmount() {
        return taxAmount;
    }

    /**
     * Sets the value of the taxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxAmount(BigDecimal value) {
        this.taxAmount = value;
    }

    /**
     * Gets the value of the seqNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqNo(String value) {
        this.seqNo = value;
    }

    /**
     * Gets the value of the productTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductTypeDesc() {
        return productTypeDesc;
    }

    /**
     * Sets the value of the productTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductTypeDesc(String value) {
        this.productTypeDesc = value;
    }

    /**
     * Gets the value of the goodsDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * Sets the value of the goodsDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsDesc(String value) {
        this.goodsDesc = value;
    }

    /**
     * Gets the value of the degree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDegree() {
        return degree;
    }

    /**
     * Sets the value of the degree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDegree(String value) {
        this.degree = value;
    }

    /**
     * Gets the value of the goodsSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodsSize() {
        return goodsSize;
    }

    /**
     * Sets the value of the goodsSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsSize(String value) {
        this.goodsSize = value;
    }

    /**
     * Gets the value of the goodsPiece property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGoodsPiece() {
        return goodsPiece;
    }

    /**
     * Sets the value of the goodsPiece property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGoodsPiece(BigDecimal value) {
        this.goodsPiece = value;
    }

    /**
     * Gets the value of the goodsQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGoodsQuantity() {
        return goodsQuantity;
    }

    /**
     * Sets the value of the goodsQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGoodsQuantity(BigDecimal value) {
        this.goodsQuantity = value;
    }

    /**
     * Gets the value of the taxByValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxByValue() {
        return taxByValue;
    }

    /**
     * Sets the value of the taxByValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxByValue(BigDecimal value) {
        this.taxByValue = value;
    }

    /**
     * Gets the value of the taxByQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxByQuantity() {
        return taxByQuantity;
    }

    /**
     * Sets the value of the taxByQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxByQuantity(BigDecimal value) {
        this.taxByQuantity = value;
    }

    /**
     * Gets the value of the taxByQuantityOver property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxByQuantityOver() {
        return taxByQuantityOver;
    }

    /**
     * Sets the value of the taxByQuantityOver property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxByQuantityOver(BigDecimal value) {
        this.taxByQuantityOver = value;
    }

    /**
     * Gets the value of the taxByQuantityWithOver property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxByQuantityWithOver() {
        return taxByQuantityWithOver;
    }

    /**
     * Sets the value of the taxByQuantityWithOver property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxByQuantityWithOver(BigDecimal value) {
        this.taxByQuantityWithOver = value;
    }

    /**
     * Gets the value of the netTaxByValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetTaxByValue() {
        return netTaxByValue;
    }

    /**
     * Sets the value of the netTaxByValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetTaxByValue(BigDecimal value) {
        this.netTaxByValue = value;
    }

    /**
     * Gets the value of the netTaxByQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetTaxByQuantity() {
        return netTaxByQuantity;
    }

    /**
     * Sets the value of the netTaxByQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetTaxByQuantity(BigDecimal value) {
        this.netTaxByQuantity = value;
    }

}
