//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2558.08.21 at 01:35:58 หลังเที่ยง ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the th.go.excise.edbarcode.ws.provider.oxm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: th.go.excise.edbarcode.ws.provider.oxm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SubmitOnlineHeader }
     * 
     */
    public SubmitOnlineHeader createSubmitOnlineHeader() {
        return new SubmitOnlineHeader();
    }

    /**
     * Create an instance of {@link TaxpayerAddressInfo }
     * 
     */
    public TaxpayerAddressInfo createTaxpayerAddressInfo() {
        return new TaxpayerAddressInfo();
    }

    /**
     * Create an instance of {@link GoodsEntryInfo }
     * 
     */
    public GoodsEntryInfo createGoodsEntryInfo() {
        return new GoodsEntryInfo();
    }

    /**
     * Create an instance of {@link BinaryInformation }
     * 
     */
    public BinaryInformation createBinaryInformation() {
        return new BinaryInformation();
    }

    /**
     * Create an instance of {@link SR12011Info }
     * 
     */
    public SR12011Info createSR12011Info() {
        return new SR12011Info();
    }

    /**
     * Create an instance of {@link PDFDocument }
     * 
     */
    public PDFDocument createPDFDocument() {
        return new PDFDocument();
    }

    /**
     * Create an instance of {@link EbarcodeSubmitOnlineRequest }
     * 
     */
    public EbarcodeSubmitOnlineRequest createEbarcodeSubmitOnlineRequest() {
        return new EbarcodeSubmitOnlineRequest();
    }

    /**
     * Create an instance of {@link SummaryInfo }
     * 
     */
    public SummaryInfo createSummaryInfo() {
        return new SummaryInfo();
    }

    /**
     * Create an instance of {@link TaxpayerInfo }
     * 
     */
    public TaxpayerInfo createTaxpayerInfo() {
        return new TaxpayerInfo();
    }

    /**
     * Create an instance of {@link EbarcodeGetSR12011ReportRequest }
     * 
     */
    public EbarcodeGetSR12011ReportRequest createEbarcodeGetSR12011ReportRequest() {
        return new EbarcodeGetSR12011ReportRequest();
    }

    /**
     * Create an instance of {@link EbarcodeGetSR12011ReportResponse }
     * 
     */
    public EbarcodeGetSR12011ReportResponse createEbarcodeGetSR12011ReportResponse() {
        return new EbarcodeGetSR12011ReportResponse();
    }

    /**
     * Create an instance of {@link DataInformation }
     * 
     */
    public DataInformation createDataInformation() {
        return new DataInformation();
    }

    /**
     * Create an instance of {@link EbarcodeSendFormSR12011Request }
     * 
     */
    public EbarcodeSendFormSR12011Request createEbarcodeSendFormSR12011Request() {
        return new EbarcodeSendFormSR12011Request();
    }

    /**
     * Create an instance of {@link GoodsListInfo }
     * 
     */
    public GoodsListInfo createGoodsListInfo() {
        return new GoodsListInfo();
    }

    /**
     * Create an instance of {@link EbarcodeSendFormSR12011Response }
     * 
     */
    public EbarcodeSendFormSR12011Response createEbarcodeSendFormSR12011Response() {
        return new EbarcodeSendFormSR12011Response();
    }

    /**
     * Create an instance of {@link EbarcodeSubmitOnlineResponse }
     * 
     */
    public EbarcodeSubmitOnlineResponse createEbarcodeSubmitOnlineResponse() {
        return new EbarcodeSubmitOnlineResponse();
    }

}
