//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2558.08.21 at 01:35:58 หลังเที่ยง ICT 
//


package th.go.excise.edbarcode.ws.provider.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SR12011Info complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SR12011Info">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaxpayerInfo" type="{http://www.excise.go.th/xsd/barcode}TaxpayerInfo" minOccurs="0"/>
 *         &lt;element name="GoodsListInfo" type="{http://www.excise.go.th/xsd/barcode}GoodsListInfo" minOccurs="0"/>
 *         &lt;element name="SummaryInfo" type="{http://www.excise.go.th/xsd/barcode}SummaryInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SR12011Info", propOrder = {
    "taxpayerInfo",
    "goodsListInfo",
    "summaryInfo"
})
public class SR12011Info {

    @XmlElement(name = "TaxpayerInfo")
    protected TaxpayerInfo taxpayerInfo;
    @XmlElement(name = "GoodsListInfo")
    protected GoodsListInfo goodsListInfo;
    @XmlElement(name = "SummaryInfo")
    protected SummaryInfo summaryInfo;

    /**
     * Gets the value of the taxpayerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TaxpayerInfo }
     *     
     */
    public TaxpayerInfo getTaxpayerInfo() {
        return taxpayerInfo;
    }

    /**
     * Sets the value of the taxpayerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxpayerInfo }
     *     
     */
    public void setTaxpayerInfo(TaxpayerInfo value) {
        this.taxpayerInfo = value;
    }

    /**
     * Gets the value of the goodsListInfo property.
     * 
     * @return
     *     possible object is
     *     {@link GoodsListInfo }
     *     
     */
    public GoodsListInfo getGoodsListInfo() {
        return goodsListInfo;
    }

    /**
     * Sets the value of the goodsListInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoodsListInfo }
     *     
     */
    public void setGoodsListInfo(GoodsListInfo value) {
        this.goodsListInfo = value;
    }

    /**
     * Gets the value of the summaryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SummaryInfo }
     *     
     */
    public SummaryInfo getSummaryInfo() {
        return summaryInfo;
    }

    /**
     * Sets the value of the summaryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SummaryInfo }
     *     
     */
    public void setSummaryInfo(SummaryInfo value) {
        this.summaryInfo = value;
    }

}
